(function(){'use strict';
 const cfg=window.SAAS_CONFIG||{};const root=window.supabase;const $=id=>document.getElementById(id);const auth=$('auth'),dash=$('dashboard'),msg=$('auth-message');let client=null,user=null,currentStore=null;
 if(root&&cfg.url&&cfg.publishableKey)client=root.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 $('year').textContent=new Date().getFullYear();
 function say(el,text,error){el.textContent=text||'';el.classList.toggle('error',!!error)}function busy(btn,on,text){if(!btn.dataset.original)btn.dataset.original=btn.textContent;btn.disabled=on;btn.textContent=on?'Aguarde…':btn.dataset.original}
 function tab(which){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===which));$('login-form').classList.toggle('hidden',which!=='login');$('signup-form').classList.toggle('hidden',which!=='signup');say(msg,'')}
 document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
 $('login-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),b=e.submitter;busy(b,true);try{if(!client)throw Error('Configure a URL e a chave publishable em config/saas.js.');const {error}=await client.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)throw error;await refresh()}catch(err){say(msg,err.message||'Não foi possível entrar.',true)}finally{busy(b,false)}});
 $('signup-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),b=e.submitter;busy(b,true);try{if(!client)throw Error('Configure o Supabase central em config/saas.js.');const {data,error}=await client.auth.signUp({email:f.get('email'),password:f.get('password'),options:{data:{full_name:f.get('name')}}});if(error)throw error;if(data.session){await refresh()}else say(msg,'Conta criada. Confira seu e-mail para confirmar o cadastro e depois entre.')}catch(err){say(msg,err.message||'Não foi possível criar a conta.',true)}finally{busy(b,false)}});
 $('forgot').addEventListener('click',async()=>{const email=$('#login-form [name=email]').value.trim();if(!email)return say(msg,'Digite seu e-mail primeiro.',true);try{const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/plataforma/'});if(error)throw error;say(msg,'Se o e-mail estiver cadastrado, você receberá instruções para redefinir a senha.')}catch(e){say(msg,e.message,true)}});
 $('logout').addEventListener('click',async()=>{if(client)await client.auth.signOut();user=null;showAuth();});function showAuth(){auth.classList.remove('hidden');dash.classList.add('hidden');$('logout').classList.add('hidden');tab('login')}
 function showDash(){auth.classList.add('hidden');dash.classList.remove('hidden');$('logout').classList.remove('hidden')}
 $('new-store-btn').addEventListener('click',()=>{$('create-panel').classList.remove('hidden');$('create-panel').scrollIntoView({behavior:'smooth',block:'start'})});$('empty-create').addEventListener('click',()=>$('new-store-btn').click());$('cancel-create').addEventListener('click',()=>$('create-panel').classList.add('hidden'));$('close-editor').addEventListener('click',()=>{$('editor').classList.add('hidden');currentStore=null});
 $('create-store-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),b=e.submitter;busy(b,true);say($('create-message'),'');try{const {data,error}=await client.rpc('saas_create_store',{p_name:f.get('name'),p_slug:f.get('slug').toLowerCase().trim(),p_whatsapp:f.get('whatsapp'),p_address:f.get('address'),p_description:f.get('description')});if(error)throw error;e.currentTarget.reset();$('create-panel').classList.add('hidden');say($('create-message'),'Loja criada com sucesso.');await loadStores();const store=Array.isArray(data)?data[0]:data;if(store)await openEditor(store.id)}catch(err){say($('create-message'),friendly(err),true)}finally{busy(b,false)}});
 function friendly(e){if(e&&e.code==='23505')return'Esse endereço já está sendo usado. Escolha outro.';return e&&e.message?e.message:'Ocorreu um erro. Verifique a configuração do Supabase e tente novamente.'}
 async function loadStores(){const {data,error}=await client.from('saas_stores').select('id,name,slug,status,whatsapp,address,description,logo_url,created_at').order('created_at',{ascending:false});if(error)throw error;const list=$('store-list');list.innerHTML='';$('empty-state').classList.toggle('hidden',!!(data&&data.length));(data||[]).forEach(s=>{const card=document.createElement('article');card.className='store-card';const h=document.createElement('h3');h.textContent=s.name;const slug=document.createElement('div');slug.className='slug';slug.textContent='/loja/?slug='+s.slug;const badge=document.createElement('span');badge.className='badge';badge.textContent=s.status==='active'?'Loja ativa':s.status;const actions=document.createElement('div');actions.className='store-actions';const edit=document.createElement('button');edit.className='ghost';edit.textContent='Editar loja';edit.addEventListener('click',()=>openEditor(s.id));const open=document.createElement('a');open.href='../loja/?slug='+encodeURIComponent(s.slug);open.target='_blank';open.rel='noopener';open.textContent='Ver cardápio';const copy=document.createElement('button');copy.className='ghost';copy.textContent='Copiar link';copy.addEventListener('click',async()=>{const url=location.origin+'/loja/?slug='+encodeURIComponent(s.slug);try{await navigator.clipboard.writeText(url);copy.textContent='Copiado!'}catch(_){prompt('Copie o link da loja:',url)}});actions.append(edit,open,copy);card.append(h,slug,badge,actions);list.append(card)});await loadPlatformAdmin()}
 async function openEditor(id){const {data,error}=await client.from('saas_stores').select('*').eq('id',id).single();if(error)throw error;currentStore=data;$('editor').classList.remove('hidden');$('editor-title').textContent=data.name;$('editor-link').textContent=location.origin+'/loja/?slug='+data.slug;const sf=$('settings-form');['id','name','whatsapp','address','description','logo_url'].forEach(k=>sf.elements[k].value=data[k]||'');const st=data.settings&&typeof data.settings==='object'?data.settings:{};sf.elements.delivery_fee.value=st.delivery_fee??st.deliveryFee??6.9;sf.elements.minimum_order.value=st.minimum_order??st.minimumOrder??0;sf.elements.payment_methods.value=Array.isArray(st.payment_methods)?st.payment_methods.join(', '):(st.payment_methods||'Pix, Dinheiro, Cartão de crédito, Cartão de débito');sf.elements.delivery_time.value=st.delivery_time||'';$('product-form').elements.store_id.value=id;await loadProducts(id);$('editor').scrollIntoView({behavior:'smooth',block:'start'})}
 $('settings-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),b=e.submitter;busy(b,true);try{const id=f.get('id');const {data:existing,error:readError}=await client.from('saas_stores').select('settings').eq('id',id).single();if(readError)throw readError;const oldSettings=existing.settings&&typeof existing.settings==='object'?existing.settings:{};const paymentMethods=String(f.get('payment_methods')||'Pix').split(',').map(v=>v.trim()).filter(Boolean).slice(0,12);const settings={...oldSettings,delivery_fee:Math.max(0,Number(f.get('delivery_fee')||0)),minimum_order:Math.max(0,Number(f.get('minimum_order')||0)),payment_methods:paymentMethods,delivery_time:String(f.get('delivery_time')||'').trim()};const {error}=await client.from('saas_stores').update({name:f.get('name'),whatsapp:String(f.get('whatsapp')||'').replace(/[^0-9]/g,''),address:f.get('address'),description:f.get('description'),logo_url:f.get('logo_url'),settings}).eq('id',id);if(error)throw error;say($('editor-message'),'Dados da loja salvos.');await loadStores();await openEditor(id)}catch(err){say($('editor-message'),friendly(err),true)}finally{busy(b,false)}});
 $('product-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),b=e.submitter;busy(b,true);try{const {error}=await client.from('saas_products').insert({store_id:f.get('store_id'),name:f.get('name'),price:Number(f.get('price')),category:f.get('category'),image_url:f.get('image_url'),description:f.get('description')});if(error)throw error;e.currentTarget.reset();$('product-form').elements.store_id.value=currentStore.id;say($('editor-message'),'Produto adicionado.');await loadProducts(currentStore.id)}catch(err){say($('editor-message'),friendly(err),true)}finally{busy(b,false)}});
 async function loadProducts(id){const {data,error}=await client.from('saas_products').select('id,name,price,category,available').eq('store_id',id).order('sort_order').order('created_at');if(error)throw error;const box=$('products-list');box.innerHTML='';if(!data.length){box.innerHTML='<p class="muted">Nenhum produto cadastrado ainda.</p>';return}data.forEach(p=>{const row=document.createElement('div');row.className='product-row';const info=document.createElement('div');const title=document.createElement('strong');title.textContent=p.name;const sub=document.createElement('small');sub.textContent=p.category+' · '+Number(p.price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})+(p.available?'':' · indisponível');info.append(title,sub);const del=document.createElement('button');del.textContent='Excluir';del.addEventListener('click',async()=>{if(!confirm('Excluir '+p.name+'?'))return;const {error}=await client.from('saas_products').delete().eq('id',p.id);if(error)say($('editor-message'),friendly(error),true);else await loadProducts(id)});row.append(info,del);box.append(row)})}
 async function loadPlatformAdmin(){try{const {data:admins,error:aerr}=await client.from('saas_platform_admins').select('user_id').limit(1);if(aerr||!admins||!admins.length)return;$('platform-admin').classList.remove('hidden');const {data:stores,error}=await client.from('saas_stores').select('id,name,slug,status,created_at').order('created_at',{ascending:false});if(error)throw error;const {data:subs}=await client.from('saas_subscriptions').select('status');const active=(subs||[]).filter(s=>s.status==='active').length;$('platform-stats').innerHTML='<div><b>'+stores.length+'</b><span>Lojas registradas</span></div><div><b>'+active+'</b><span>Assinaturas ativas</span></div><div><b>'+(subs||[]).filter(s=>s.status==='trial').length+'</b><span>Em período de teste</span></div>';const list=$('platform-stores');list.innerHTML='';stores.forEach(s=>{const row=document.createElement('div');row.className='table-row';const a=document.createElement('span');a.textContent=s.name+' · '+s.slug;const b=document.createElement('small');b.textContent=s.status;row.append(a,b);list.append(row)})}catch(e){console.warn('Painel admin não carregado',e)}}
 async function refresh(){if(!client){showAuth();say(msg,'Configure o Supabase central em config/saas.js.',true);return}try{const {data,error}=await client.auth.getUser();if(error)throw error;user=data.user;if(!user){showAuth();return}showDash();await loadStores()}catch(e){showAuth();say(msg,friendly(e),true)}}
 if(client)client.auth.onAuthStateChange(()=>{setTimeout(refresh,0)});refresh();
})();
