(function(){'use strict';
const cfg=window.LOJA&&window.LOJA.supabase;const authPanel=document.getElementById('authPanel'),appPanel=document.getElementById('appPanel');let sb=null,stores=[],selectedStore=null;
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function message(id,msg,type){const el=$(id);el.textContent=msg;el.className='status show'+(type?' '+type:'');}function clear(id){$(id).className='status';$(id).textContent='';}function setBusy(id,busy,label){const el=$(id);el.disabled=busy;if(label){if(!el.dataset.original)el.dataset.original=el.textContent;el.textContent=busy?label:el.dataset.original;}}
function slugify(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48)}
if(!window.supabase||!cfg||!cfg.enabled||!cfg.url||!cfg.publishableKey){message('authStatus','Supabase não está configurado. Peça ao administrador para configurar a plataforma usando somente a chave pública (publishable).','error');['signIn','signUp'].forEach(id=>$(id).disabled=true);return;}
sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
$('storeName').addEventListener('input',()=>{if(!$('storeSlug').dataset.edited)$('storeSlug').value=slugify($('storeName').value)});$('storeSlug').addEventListener('input',()=>{$('storeSlug').dataset.edited='1';$('storeSlug').value=slugify($('storeSlug').value)});
$('signIn').addEventListener('click',async e=>{e.preventDefault();clear('authStatus');setBusy('signIn',true,'Entrando…');try{const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;await init()}catch(e){message('authStatus',friendly(e),'error')}finally{setBusy('signIn',false)}});
$('signUp').addEventListener('click',async e=>{e.preventDefault();clear('authStatus');const email=$('email').value.trim(),password=$('password').value,name=$('fullName').value.trim();if(!name){message('authStatus','Informe seu nome para criar a conta.','error');return}if(password.length<8){message('authStatus','Use uma senha com pelo menos 8 caracteres.','error');return}setBusy('signUp',true,'Criando…');try{const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;if(data.session){await init()}else{message('authStatus','Conta criada. Confirme seu e-mail pelo link enviado e depois volte aqui para entrar e cadastrar sua loja.','good')}}catch(e){message('authStatus',friendly(e),'error')}finally{setBusy('signUp',false)}});
$('signOut').addEventListener('click',async()=>{await sb.auth.signOut();appPanel.classList.add('hidden');authPanel.classList.remove('hidden');$('password').value='';});$('refresh').addEventListener('click',loadStores);
$('storeForm').addEventListener('submit',async e=>{e.preventDefault();clear('appStatus');const user=(await sb.auth.getUser()).data.user;if(!user){message('appStatus','Sua sessão expirou. Entre novamente.','error');return}const payload={owner_id:user.id,name:$('storeName').value.trim(),slug:$('storeSlug').value.trim(),whatsapp:$('storeWhats').value.replace(/\D/g,''),address:$('storeAddress').value.trim()||null,description:$('storeDescription').value.trim()||null,logo_url:$('storeLogo').value.trim()||null,banner_url:$('storeBanner').value.trim()||null,status:'pending'};if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(payload.slug)){message('appStatus','O link deve conter apenas letras minúsculas, números e hífens.','error');return}if(!/^\d{12,13}$/.test(payload.whatsapp)){message('appStatus','Informe WhatsApp com código do país, DDD e número. Ex.: 5511999999999','error');return}setBusy('createStore',true,'Salvando loja…');try{const {data,error}=await sb.from('stores').insert(payload).select('id,name,slug,status').single();if(error)throw error;$('storeForm').reset();$('storeSlug').dataset.edited='';message('appStatus','Loja cadastrada! Ela ficará em análise até ser aprovada pela administração.','good');await loadStores();if(data)selectStore(data.id)}catch(e){message('appStatus',friendly(e),'error')}finally{setBusy('createStore',false)}});
$('productForm').addEventListener('submit',async e=>{e.preventDefault();clear('appStatus');if(!selectedStore){message('appStatus','Selecione uma loja antes de cadastrar produtos.','error');return}setBusy('addProduct',true,'Salvando produto…');try{const p={store_id:selectedStore.id,name:$('productName').value.trim(),price:Number($('productPrice').value),category:$('productCategory').value.trim()||'Cardápio',image_url:$('productImage').value.trim()||null,description:$('productDescription').value.trim()||null,is_available:true};const {error}=await sb.from('store_products').insert(p);if(error)throw error;$('productForm').reset();$('productStoreId').value=selectedStore.id;message('appStatus','Produto adicionado.','good');await loadProducts()}catch(e){message('appStatus',friendly(e),'error')}finally{setBusy('addProduct',false)}});
async function init(){const {data,error}=await sb.auth.getUser();if(error||!data.user){authPanel.classList.remove('hidden');appPanel.classList.add('hidden');return}authPanel.classList.add('hidden');appPanel.classList.remove('hidden');$('userEmail').textContent=data.user.email||'';$('welcome').textContent='Olá, '+(data.user.user_metadata?.full_name||'lojista');await loadStores()}
async function loadStores(){if(!sb)return;const {data:userData}=await sb.auth.getUser();if(!userData.user)return;const list=$('storeList');list.innerHTML='<p class="muted">Carregando…</p>';try{const {data,error}=await sb.from('stores').select('id,name,slug,status,whatsapp,address,description,created_at').eq('owner_id',userData.user.id).order('created_at',{ascending:false});if(error)throw error;stores=data||[];if(!stores.length){list.innerHTML='<p class="muted">Você ainda não cadastrou nenhuma loja. Preencha o formulário acima para começar.</p>';$('productsSection').classList.add('hidden');return}list.innerHTML=stores.map(s=>`<article class="store-card"><div class="store-head"><div><strong>${esc(s.name)}</strong><div class="muted">Slug: ${esc(s.slug)} · WhatsApp: ${esc(s.whatsapp)}</div></div><span class="tag ${s.status==='published'?'live':''}">${s.status==='published'?'Publicada':s.status==='rejected'?'Precisa de ajustes':'Em análise'}</span></div><div class="actions"><button class="btn secondary" data-select="${esc(s.id)}">Gerenciar produtos</button>${s.status==='published'?`<a class="btn" style="text-decoration:none;display:inline-flex;align-items:center" target="_blank" rel="noopener" href="../loja/?slug=${encodeURIComponent(s.slug)}">Abrir loja</a>`:''}</div></article>`).join('');list.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>selectStore(b.dataset.select)));if(selectedStore){const fresh=stores.find(s=>s.id===selectedStore.id);if(fresh)selectStore(fresh.id);else $('productsSection').classList.add('hidden')}}catch(e){list.innerHTML='<p class="muted">Não foi possível carregar suas lojas.</p>';message('appStatus',friendly(e),'error')}}
async function selectStore(id){selectedStore=stores.find(s=>s.id===id)||null;if(!selectedStore)return;$('productsSection').classList.remove('hidden');$('productHeading').textContent='Produtos · '+selectedStore.name;$('productStoreId').value=selectedStore.id;await loadProducts()}
async function loadProducts(){if(!selectedStore)return;const el=$('productList');el.innerHTML='<p class="muted">Carregando produtos…</p>';try{const {data,error}=await sb.from('store_products').select('id,name,price,category,image_url,description,is_available').eq('store_id',selectedStore.id).order('created_at',{ascending:false});if(error)throw error;if(!data.length){el.innerHTML='<p class="muted">Nenhum produto ainda. Use o formulário acima para adicionar o primeiro.</p>';return}el.innerHTML=data.map(p=>`<article class="product-card">${p.image_url?`<img src="${esc(p.image_url)}" alt="" loading="lazy" onerror="this.style.display='none'">`:''}<h3>${esc(p.name)}</h3><div class="muted">${esc(p.category||'Cardápio')}</div><div class="price">${Number(p.price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div><p class="muted">${esc(p.description||'')}</p><button class="btn danger" data-delete="${esc(p.id)}">Excluir produto</button></article>`).join('');el.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Excluir este produto?'))return;b.disabled=true;const {error}=await sb.from('store_products').delete().eq('id',b.dataset.delete);if(error){message('appStatus',friendly(error),'error');b.disabled=false;return}await loadProducts()}))}catch(e){el.innerHTML='<p class="muted">Não foi possível carregar os produtos.</p>';message('appStatus',friendly(e),'error')}}
function friendly(e){const m=e&&e.message?e.message:String(e||'Erro desconhecido');if(/Failed to fetch|NetworkError/i.test(m))return'Não foi possível conectar ao Supabase. Verifique a internet e a URL do projeto.';if(/Invalid login credentials/i.test(m))return'E-mail ou senha incorretos.';if(/duplicate key|stores_slug_key|store.*slug/i.test(m))return'Esse link já está em uso. Escolha outro slug.';if(/relation .* does not exist|schema cache/i.test(m))return'O banco ainda não está preparado. O administrador precisa executar supabase/store-builder.sql no SQL Editor do Supabase.';if(/row-level security|permission denied/i.test(m))return'O banco bloqueou a operação por segurança. Confira as políticas RLS da migração supabase/store-builder.sql.';if(/User already registered/i.test(m))return'Esse e-mail já tem conta. Use Entrar ou recupere sua senha.';return m}
sb.auth.onAuthStateChange((event)=>{if(event==='SIGNED_IN'||event==='TOKEN_REFRESHED')setTimeout(init,0)});sb.auth.getSession().then(init).catch(e=>message('authStatus',friendly(e),'error'));
})();
