
(() => { const S=window.PLATFORM; let client=null, user=null, tab='overview'; const $=s=>document.querySelector(s); const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((v||0));
function app(){document.body.innerHTML=`<div id="root"></div>`; boot()}
async function boot(){ if(!S.supabase.url||!S.supabase.publishableKey){return login('Configure a URL e Publishable Key do Supabase para iniciar o Super Admin.')} client=window.supabase.createClient(S.supabase.url,S.supabase.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}); const {data}=await client.auth.getSession(); user=data.session?.user; user?await load():login(); client.auth.onAuthStateChange((_e,s)=>{user=s?.user;if(user)load();}); }
function login(msg=''){ $('#root').innerHTML=`<div class="login card"><h1>Super Admin</h1><p class="muted">${S.name} 2.0</p><form id="f"><input id="email" type="email" placeholder="E-mail" required style="width:100%;margin:7px 0"><input id="pass" type="password" placeholder="Senha" required style="width:100%;margin:7px 0"><button class="primary" style="width:100%;margin-top:8px">Entrar</button><div class="error">${msg}</div></form></div>`;$('#f').onsubmit=async e=>{e.preventDefault();const r=await client.auth.signInWithPassword({email:$('#email').value,password:$('#pass').value});if(r.error)return login(r.error.message);load()}}
async function load(){const {data:m,error}=await client.from('organization_members').select('role,status').eq('user_id',user.id).eq('status','ACTIVE').maybeSingle();if(error||!m||m.role!=='SUPER_ADMIN')return login('Este usuário não possui a função SUPER_ADMIN. Vincule-o em organization_members.');render();}
async function q(table){const r=await client.from(table).select('*',{count:'exact',head:false}).limit(1000);return r.data||[]}
async function render(){let orgs=[],stores=[],subs=[],orders=[];try{[orgs,stores,subs,orders]=await Promise.all([q('organizations'),q('stores'),q('subscriptions'),q('orders_v2')])}catch(e){} const active=orgs.filter(x=>x.status==='ATIVA').length,trial=orgs.filter(x=>x.status==='TRIAL').length,susp=orgs.filter(x=>x.status==='SUSPENSA').length,revenue=orders.filter(x=>x.payment_status==='PAID').reduce((a,x)=>a+Number(x.total||0),0); $('#root').innerHTML=`<div class="wrap"><aside class="side"><div class="brand">🍔 Sistema 2.0</div><div class="nav">${[['overview','📊 Visão Geral'],['orgs','🏪 Lojas'],['users','👥 Usuários'],['subs','💳 Assinaturas'],['orders','📦 Pedidos'],['logs','🧾 Auditoria']].map(([id,t])=>`<button class="${tab===id?'active':''}" data-tab="${id}">${t}</button>`).join('')}<button id="logout">↪ Sair</button></div></aside><main class="main"><div class="top"><div><h1>${title()}</h1><div class="muted">Gestão SaaS multiempresa</div></div><span class="badge">SUPER_ADMIN</span></div><section id="content"></section></main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('#logout').onclick=()=>client.auth.signOut();content({orgs,stores,subs,orders,revenue,active,trial,susp});}
function title(){return ({overview:'Visão Geral',orgs:'Lojas',users:'Usuários',subs:'Assinaturas',orders:'Pedidos',logs:'Auditoria'})[tab]}
function content(d){let c=$('#content'); if(tab==='overview'){c.innerHTML=`<div class="grid"><div class="card">Lojas ativas<div class="metric">${d.active}</div></div><div class="card">Trial<div class="metric">${d.trial}</div></div><div class="card">Suspensas<div class="metric">${d.susp}</div></div><div class="card">Vendas processadas<div class="metric">${money(d.revenue)}</div></div></div><div class="card" style="margin-top:16px"><h2>Resumo</h2><p class="muted">Pedidos: ${d.orders.length} · Lojas: ${d.stores.length} · Assinaturas: ${d.subs.length}</p></div>`} else if(tab==='orgs'){c.innerHTML=`<div class="toolbar"><input id="search" placeholder="Buscar loja..."><button class="primary" id="new">Nova organização</button></div><div class="card"><table class="table"><thead><tr><th>Nome</th><th>Slug</th><th>Status</th><th>Criada</th></tr></thead><tbody>${d.orgs.map(o=>`<tr><td>${esc(o.name)}</td><td>${esc(o.slug)}</td><td>${o.status}</td><td>${new Date(o.created_at).toLocaleDateString('pt-BR')}</td></tr>`).join('')}</tbody></table></div>`;$('#new').onclick=()=>alert('Criação segura deve ser feita por Edge Function/service backend para criar organização + primeiro OWNER sem expor privilégios no navegador.');} else if(tab==='orders'){c.innerHTML=`<div class="card"><table class="table"><thead><tr><th>Pedido</th><th>Status</th><th>Pagamento</th><th>Total</th></tr></thead><tbody>${d.orders.slice(0,100).map(o=>`<tr><td>#${esc(o.order_number)}</td><td>${o.status}</td><td>${o.payment_status}</td><td>${money(o.total)}</td></tr>`).join('')}</tbody></table></div>`} else if(tab==='subs'){c.innerHTML=`<div class="card"><table class="table"><thead><tr><th>Organização</th><th>Status</th><th>Plano</th><th>Renovação</th></tr></thead><tbody>${d.subs.map(s=>`<tr><td>${esc(s.organization_id)}</td><td>${s.status}</td><td>${esc(s.plan_id||'-')}</td><td>${s.renews_at?new Date(s.renews_at).toLocaleDateString('pt-BR'):'-'}</td></tr>`).join('')}</tbody></table></div>`} else if(tab==='users'){c.innerHTML='<div class="card"><p>Usuários são gerenciados pelo Supabase Auth e vinculados por organization_members. A atribuição de SUPER_ADMIN não é feita automaticamente pelo cadastro.</p></div>'} else {c.innerHTML='<div class="card"><p>Auditoria centralizada em <code>audit_logs</code>. O histórico completo é protegido por RLS e disponível apenas para SUPER_ADMIN ou membros autorizados da organização.</p></div>'}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))} window.addEventListener('load',app); })();
