/* Central de Operações — Admin Gerador.
   Front-end seguro: usa apenas a Publishable key do Supabase + RLS/store_admins. */
(function () {
  'use strict';
  var root = document.getElementById('raiz');
  if (!root) return;
  var DB_NAME = 'admin-gerador', STORE = 'lojas';
  var C = { page:'dashboard', loja:null, session:null, client:null, orders:[], loading:false, busca:'', status:'all', period:'all', detalhe:null, detalheItens:[], realtime:null, autoRefresh:null, _stores:[], lastSync:null, loadError:null };
  var STATUSES = [
    ['all','Todos'],['whatsapp_pending','Aguardando WhatsApp'],['received','Recebido'],['confirmed','Confirmado'],
    ['preparing','Em preparo'],['ready','Pronto'],['out_for_delivery','Saiu para entrega'],['completed','Concluído'],['cancelled','Cancelado']
  ];
  var PERIODS = [['all','Todo o período'],['today','Hoje'],['7d','Últimos 7 dias'],['30d','Últimos 30 dias']];
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function money(n){return (+n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
  function date(v){if(!v)return '—';var d=new Date(v);return d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});}
  function dayKey(v){var d=new Date(v);return isNaN(d)?'':d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  function idb(){return new Promise(function(ok,err){var r=indexedDB.open(DB_NAME,1);r.onsuccess=function(){ok(r.result)};r.onerror=function(){err(r.error)}})}
  function stores(){return idb().then(function(db){return new Promise(function(ok,err){var q=db.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=function(){ok(q.result||[])};q.onerror=function(){err(q.error)}})}).then(function(a){return a.sort(function(x,y){return (x.nome||'').localeCompare(y.nome||'')})})}
  function clientFor(l){if(!window.supabase||!window.supabase.createClient)return null;if(!l||!l.supabase||!l.supabase.enabled||!l.supabase.url||!l.supabase.publishableKey)return null;return window.supabase.createClient(l.supabase.url,l.supabase.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'admin-central-'+(l.slug||'loja')}})}
  function toast(t){var e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.appendChild(e)}e.textContent=t;clearTimeout(window.__centralToast);window.__centralToast=setTimeout(function(){e.remove()},3000)}
  function filteredPeriod(list){var now=Date.now(),ms=C.period==='today'?86400000:C.period==='7d'?7*86400000:C.period==='30d'?30*86400000:0;if(!ms)return list;return list.filter(function(o){var t=new Date(o.created_at).getTime();return t>=now-ms});}
  function activeOrders(){return filteredPeriod(C.orders||[]);}
  function statusLabel(s){var x=STATUSES.find(function(a){return a[0]===s});return x?x[1]:s||'Sem status';}
  function statusClass(s){return s==='completed'?'ok':s==='cancelled'?'erro':s==='preparing'||s==='ready'||s==='out_for_delivery'?'acao':'aviso';}
  function modalHtml(mode){
    mode=mode||'login';var cadastro=mode==='signup';
    return '<div class="central-modal-fundo" id="central-login"><div class="central-modal central-login-modal"><div class="central-modal-icon">'+(cadastro?'👤':'🔐')+'</div><div><h2>'+(cadastro?'Criar acesso administrativo':'Entrar na Central')+'</h2><p>'+(cadastro?'Crie sua conta para solicitar acesso à operação da ':'Acesse a operação da ')+'<b>'+esc(C.loja&&C.loja.nome||'loja selecionada')+'</b>.</p></div>'+(cadastro?'<label>Nome<input id="central-name" class="inp" type="text" autocomplete="name" placeholder="Seu nome"></label>':'')+'<label>E-mail<input id="central-email" class="inp" type="email" autocomplete="email" placeholder="admin@empresa.com"></label><label>Senha<div class="central-password-wrap"><input id="central-password" class="inp" type="password" autocomplete="'+(cadastro?'new-password':'current-password')+'" placeholder="'+(cadastro?'Mínimo de 6 caracteres':'Sua senha')+'"><button type="button" class="central-password-toggle" data-central="toggle-password">Mostrar</button></div></label>'+(cadastro?'<label>Confirmar senha<input id="central-password-confirm" class="inp" type="password" autocomplete="new-password" placeholder="Repita sua senha"></label>':'')+'<div class="central-login-options">'+(cadastro?'<button type="button" class="link-btn" data-central="show-login">Já tenho uma conta</button>':'<div><button type="button" class="link-btn" data-central="reset-password">Esqueci minha senha</button> · <button type="button" class="link-btn" data-central="show-signup">Criar cadastro</button></div>')+'<span>Supabase Auth</span></div><div id="central-login-msg" class="central-msg"></div><div class="acoes central-login-actions"><button class="btn" data-central="fechar-login">Cancelar</button><button class="btn primario" id="central-login-submit" data-central="'+(cadastro?'signup':'login')+'">'+(cadastro?'Criar cadastro':'Entrar')+'</button></div><small>'+(cadastro?'O cadastro não libera acesso automaticamente. Um administrador precisa vincular sua conta à loja em <code>public.store_admins</code>.':'O acesso é controlado pelo Supabase e pelas políticas RLS.')+'</small></div></div>';
  }
  function injectNav(){
    var topo=root.querySelector('.topo-lista');if(!topo||root.querySelector('.central-nav'))return;
    var nav=document.createElement('div');nav.className='central-nav';nav.innerHTML='<div class="central-brand"><b>Central</b><span>Operação multi-lojas</span></div><div class="central-links"><button data-central="dashboard">📊 Visão geral</button><button data-central="pedidos">🛒 Pedidos</button><button data-central="clientes">👥 Clientes</button><button data-central="cozinha">👨‍🍳 Cozinha</button><button data-central="caixa">💰 Caixa</button><button data-central="fidelidade">🏆 Fidelidade</button></div>';
    topo.parentNode.insertBefore(nav,topo);
  }
  function centralHeader(title,sub){return '<div class="central-header"><div><small>ADMIN GERADOR · CENTRAL</small><h1>'+title+'</h1><p>'+sub+'</p></div><div class="central-head-actions"><select id="central-store" class="inp">'+(C._stores||[]).map(function(l){return '<option value="'+esc(l.id)+'" '+(C.loja&&C.loja.id===l.id?'selected':'')+'>'+esc(l.nome)+' · '+esc(l.slug)+'</option>'}).join('')+'</select><span class="central-live '+(C.realtime?'on':'')+'"><i></i>'+(C.realtime?'Tempo real':'Atualização manual')+'</span><button class="btn fantasma" data-central="logout">Sair</button></div></div>';}
  function metrics(o){var total=o.reduce(function(s,x){return s+(+x.total||0)},0),open=o.filter(function(x){return !['completed','cancelled'].includes(x.status)}).length,done=o.filter(function(x){return x.status==='completed'}).length,customers=uniqueCustomers(o).length,avg=o.length?total/o.length:0,rate=o.length?Math.round(done/o.length*100):0;return '<div class="central-metrics"><div><b>'+o.length+'</b><span>Pedidos</span><small>no período</small></div><div><b>'+money(total)+'</b><span>Faturamento</span><small>valor bruto</small></div><div><b>'+money(avg)+'</b><span>Ticket médio</span><small>por pedido</small></div><div><b>'+open+'</b><span>Em aberto</span><small>aguardando ação</small></div><div><b>'+customers+'</b><span>Clientes</span><small>identificados</small></div><div><b>'+rate+'%</b><span>Conclusão</span><small>'+done+' concluídos</small></div></div>';}
  function uniqueCustomers(o){var m={};o.forEach(function(x){var k=(x.customer_phone||x.customer_name||'').trim().toLowerCase();if(k)m[k]=1});return Object.keys(m);}
  function dashboard(){
    var o=activeOrders(),total=o.reduce(function(s,x){return s+(+x.total||0)},0),open=o.filter(function(x){return !['completed','cancelled'].includes(x.status)}),statusCounts={};o.forEach(function(x){statusCounts[x.status]=(statusCounts[x.status]||0)+1});
    var recent=o.slice().sort(function(a,b){return new Date(b.created_at)-new Date(a.created_at)}).slice(0,6);
    var top=o.slice().sort(function(a,b){return (+b.total||0)-(+a.total||0)}).slice(0,5);
    var byDay={};o.forEach(function(x){var k=dayKey(x.created_at);if(k)byDay[k]=(byDay[k]||0)+(+x.total||0)});var days=Object.keys(byDay).sort().slice(-7),maxDay=Math.max.apply(Math,days.map(function(k){return byDay[k]}).concat([1]));
    var bestCustomer=customers().slice(0,5),sync=C.lastSync?date(C.lastSync):'Ainda não sincronizado';
    return centralHeader('📊 Visão geral','Acompanhe a operação, pedidos, clientes e desempenho da loja.')+
      '<div class="central-period"><div><b>Período</b><span>Indicadores da operação</span></div><div class="central-period-actions">'+PERIODS.map(function(p){return '<button class="btn '+(C.period===p[0]?'primario':'')+'" data-central="period" data-period="'+p[0]+'">'+p[1]+'</button>'}).join('')+'</div></div>'+metrics(o)+
      '<div class="central-grid-2"><section class="central-card"><div class="central-card-head"><div><b>Pedidos por status</b><span>Distribuição no período selecionado</span></div><button class="btn" data-central="pedidos">Ver pedidos</button></div><div class="status-resumo">'+STATUSES.slice(1).map(function(s){return '<div><span><i class="dot '+statusClass(s[0])+'"></i>'+s[1]+'</span><b>'+((statusCounts[s[0]]||0))+'</b></div>'}).join('')+'</div></section><section class="central-card"><div class="central-card-head"><div><b>Saúde da loja</b><span>Conectividade e operação</span></div></div><div class="saude-lista"><div><span>Supabase</span><b class="'+(C.client?'saude-ok':'saude-erro')+'">'+(C.client?'Configurado':'Não configurado')+'</b></div><div><span>Autenticação</span><b class="'+(C.session?'saude-ok':'saude-aviso')+'">'+(C.session?'Conectado':'Não conectado')+'</b></div><div><span>Tempo real</span><b class="'+(C.realtime?'saude-ok':'saude-aviso')+'">'+(C.realtime?'Ativo':'Indisponível')+'</b></div><div><span>Pedidos carregados</span><b>'+C.orders.length+'</b></div></div></section></div>'+
      '<div class="central-card central-performance"><div class="central-card-head"><div><b>Desempenho dos últimos dias</b><span>Faturamento por dia no período selecionado</span></div><span class="central-sync">Sincronizado '+esc(sync)+'</span></div><div class="central-bars">'+(days.length?days.map(function(k){var d=new Date(k+'T12:00:00');return '<div class="central-bar-col"><span>'+money(byDay[k])+'</span><div class="central-bar" style="height:'+Math.max(8,Math.round(byDay[k]/maxDay*110))+'px"></div><small>'+d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})+'</small></div>'}).join(''):'<div class="central-empty compact"><b>Sem dados de faturamento.</b></div>')+'</div></section><section class="central-card"><div class="central-card-head"><div><b>Clientes de maior valor</b><span>Relacionamento no período</span></div><button class="btn" data-central="clientes">Ver clientes</button></div><div class="recent-list">'+(bestCustomer.length?bestCustomer.map(function(c){return '<div class="customer-mini"><span><b>'+esc(c.name)+'</b><small>'+esc(c.phone||'Sem telefone')+' · '+c.orders+' pedido(s)</small></span><strong>'+money(c.total)+'</strong></div>'}).join(''):'<div class="central-empty compact"><b>Nenhum cliente.</b></div>')+'</div></section></div>'+
      '<div class="central-grid-2"><section class="central-card"><div class="central-card-head"><div><b>Pedidos recentes</b><span>Últimas movimentações</span></div><button class="btn" data-central="refresh">↻ Atualizar</button></div><div class="recent-list">'+(recent.length?recent.map(function(x){return '<button class="recent-row" data-central="pedido" data-id="'+esc(x.id)+'"><span><b>#'+esc(x.order_number)+'</b><small>'+esc(x.customer_name||'Cliente')+' · '+date(x.created_at)+'</small></span><strong>'+money(x.total)+'</strong><i class="selo '+statusClass(x.status)+'">'+esc(statusLabel(x.status))+'</i></button>'}).join(''):'<div class="central-empty compact"><b>Nenhum pedido no período.</b></div>')+'</div></section><section class="central-card"><div class="central-card-head"><div><b>Maiores pedidos</b><span>Por valor</span></div></div><div class="recent-list">'+(top.length?top.map(function(x){return '<button class="recent-row" data-central="pedido" data-id="'+esc(x.id)+'"><span><b>#'+esc(x.order_number)+'</b><small>'+esc(x.customer_name||'Cliente')+'</small></span><strong>'+money(x.total)+'</strong></button>'}).join(''):'<div class="central-empty compact"><b>Nenhum pedido.</b></div>')+'</div></section></div>'+
      '<div class="central-actions-bar"><button class="btn primario" data-central="pedidos">🛒 Gerenciar pedidos</button><button class="btn" data-central="clientes">👥 Ver clientes</button><button class="btn" data-central="export-csv">⬇ Exportar CSV</button></div>';
  }
  function filtered(){var q=(C.busca||'').toLowerCase();return activeOrders().filter(function(o){if(C.status&&C.status!=='all'&&o.status!==C.status)return false;if(!q)return true;return [o.order_number,o.customer_name,o.customer_phone,o.delivery_address,o.payment_method,o.status].join(' ').toLowerCase().includes(q)});}
  function ordersTable(){var a=filtered();if(C.loading)return '<div class="central-empty"><b>Carregando pedidos…</b><span>Consultando o Supabase com as permissões da loja.</span></div>';if(!a.length)return '<div class="central-empty"><div>🛒</div><b>Nenhum pedido encontrado</b><span>Ajuste a busca, status ou período.</span></div>';return '<div class="central-table-wrap"><table class="central-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Tipo</th><th>Pagamento</th><th>Total</th><th>Status</th><th>Data</th></tr></thead><tbody>'+a.map(function(o){return '<tr data-central="pedido" data-id="'+esc(o.id)+'"><td><b>#'+esc(o.order_number)+'</b></td><td><b>'+esc(o.customer_name||'Cliente')+'</b><small>'+esc(o.customer_phone||'')+'</small></td><td>'+esc(o.order_type==='delivery'?'Entrega':'Retirada')+'</td><td>'+esc(o.payment_method||'—')+'</td><td><b>'+money(o.total)+'</b></td><td><span class="selo '+statusClass(o.status)+'">'+esc(statusLabel(o.status))+'</span></td><td>'+date(o.created_at)+'</td></tr>'}).join('')+'</tbody></table></div>';}
  function pageOrders(){return centralHeader('🛒 Pedidos','Controle o fluxo de pedidos em tempo real.')+metrics(activeOrders())+'<div class="central-toolbar"><input id="central-search" class="inp" placeholder="Buscar pedido, cliente, telefone…" value="'+esc(C.busca)+'"><select id="central-status" class="inp">'+STATUSES.map(function(s){return '<option value="'+s[0]+'" '+(C.status===s[0]?'selected':'')+'>'+s[1]+'</option>'}).join('')+'</select><select id="central-period" class="inp">'+PERIODS.map(function(p){return '<option value="'+p[0]+'" '+(C.period===p[0]?'selected':'')+'>'+p[1]+'</option>'}).join('')+'</select><button class="btn" data-central="refresh">↻ Atualizar</button><button class="btn" data-central="export-csv">⬇ CSV</button><span class="central-user">● '+esc(C.session&&C.session.user&&C.session.user.email||'Administrador')+'</span></div>'+ordersTable()+(C.detalhe?detail():'');}
  function customers(){var map={};activeOrders().forEach(function(o){var k=(o.customer_phone||o.customer_name||'').trim().toLowerCase();if(!k)return;if(!map[k])map[k]={name:o.customer_name||'Cliente',phone:o.customer_phone||'',orders:0,total:0,last:o.created_at};map[k].orders++;map[k].total+=(+o.total||0);if(new Date(o.created_at)>new Date(map[k].last))map[k].last=o.created_at});return Object.keys(map).map(function(k){return map[k]}).sort(function(a,b){return b.total-a.total});}
  function pageCustomers(){var a=customers(),q=(C.busca||'').toLowerCase();if(q)a=a.filter(function(c){return (c.name+' '+c.phone).toLowerCase().includes(q)});return centralHeader('👥 Clientes','Base de clientes formada pelos pedidos da loja.')+'<div class="central-toolbar"><input id="central-search" class="inp" placeholder="Buscar cliente ou telefone…" value="'+esc(C.busca)+'"><select id="central-period" class="inp">'+PERIODS.map(function(p){return '<option value="'+p[0]+'" '+(C.period===p[0]?'selected':'')+'>'+p[1]+'</option>'}).join('')+'</select><button class="btn" data-central="refresh">↻ Atualizar</button><button class="btn" data-central="export-csv">⬇ CSV</button></div><div class="central-metrics"><div><b>'+a.length+'</b><span>Clientes</span></div><div><b>'+money(a.reduce(function(s,c){return s+c.total},0))+'</b><span>Faturamento</span></div><div><b>'+((a.reduce(function(s,c){return s+c.orders},0)/Math.max(a.length,1)).toFixed(1))+'</b><span>Pedidos por cliente</span></div><div><b>'+money(a.length?a.reduce(function(s,c){return s+c.total},0)/a.length:0)+'</b><span>Valor médio/cliente</span></div></div><div class="central-table-wrap"><table class="central-table"><thead><tr><th>Cliente</th><th>Telefone</th><th>Pedidos</th><th>Total</th><th>Último pedido</th></tr></thead><tbody>'+(a.length?a.map(function(c){return '<tr><td><b>'+esc(c.name)+'</b></td><td>'+esc(c.phone||'—')+'</td><td>'+c.orders+'</td><td><b>'+money(c.total)+'</b></td><td>'+date(c.last)+'</td></tr>'}).join(''):'<tr><td colspan="5"><div class="central-empty compact"><b>Nenhum cliente encontrado.</b></div></td></tr>')+'</tbody></table></div>';}
  function kitchen(){
    var a=activeOrders().filter(function(o){return ['received','confirmed','preparing','ready','out_for_delivery'].includes(o.status)}).sort(function(a,b){return new Date(a.created_at)-new Date(b.created_at)});
    var cols=[['received','NOVOS'],['confirmed','CONFIRMADOS'],['preparing','EM PREPARO'],['ready','PRONTOS'],['out_for_delivery','EM ENTREGA']];
    return centralHeader('👨‍🍳 Cozinha','Painel operacional para acompanhar a produção em tempo real.')+
      '<div class="kitchen-board">'+cols.map(function(c){var rows=a.filter(function(o){return o.status===c[0]});return '<section class="kitchen-col"><header><b>'+c[1]+'</b><span>'+rows.length+'</span></header>'+(rows.length?rows.map(function(o){return '<article class="kitchen-ticket" data-central="pedido" data-id="'+esc(o.id)+'"><div><b>#'+esc(o.order_number)+'</b><small>'+date(o.created_at)+'</small></div><strong>'+esc(o.customer_name||'Cliente')+'</strong><p>'+esc(o.notes||'Sem observações')+'</p><div class="kitchen-actions">'+(c[0]==='received'?'<button data-central="quick-status" data-id="'+esc(o.id)+'" data-status="confirmed">Aceitar</button>':'')+(c[0]==='confirmed'?'<button data-central="quick-status" data-id="'+esc(o.id)+'" data-status="preparing">Preparar</button>':'')+(c[0]==='preparing'?'<button data-central="quick-status" data-id="'+esc(o.id)+'" data-status="ready">Pronto</button>':'')+(c[0]==='ready'?'<button data-central="quick-status" data-id="'+esc(o.id)+'" data-status="out_for_delivery">Despachar</button>':'')+(c[0]==='out_for_delivery'?'<button data-central="quick-status" data-id="'+esc(o.id)+'" data-status="completed">Concluir</button>':'')+'</div></article>'}).join(''):'<div class="central-empty compact">Nenhum pedido</div>')+'</section>'}).join('')+'</div>';
  }
  function cash(){
    var a=activeOrders().filter(function(o){return o.status!=='cancelled'}), total=a.reduce(function(s,o){return s+(+o.total||0)},0), groups={};
    a.forEach(function(o){var k=o.payment_method||'Não informado';if(!groups[k])groups[k]={count:0,total:0};groups[k].count++;groups[k].total+=(+o.total||0)});
    return centralHeader('💰 Caixa','Resumo financeiro operacional baseado nos pedidos registrados.')+
      '<div class="central-metrics"><div><b>'+money(total)+'</b><span>Vendas</span><small>sem cancelados</small></div><div><b>'+a.length+'</b><span>Transações</span><small>no período</small></div><div><b>'+money(a.length?total/a.length:0)+'</b><span>Ticket médio</span></div><div><b>'+money(a.filter(function(o){return o.payment_method&&o.payment_method.toLowerCase().includes('pix')}).reduce(function(s,o){return s+(+o.total||0)},0))+'</b><span>PIX</span></div></div>'+ 
      '<section class="central-card"><div class="central-card-head"><div><b>Por forma de pagamento</b><span>Conferência rápida</span></div><button class="btn" data-central="export-csv">⬇ Exportar</button></div><div class="status-resumo">'+Object.keys(groups).map(function(k){return '<div><span>'+esc(k)+'</span><b>'+money(groups[k].total)+' · '+groups[k].count+'</b></div>'}).join('')+'</div></section>'+
      '<section class="central-card"><div class="central-card-head"><div><b>Fechamento</b><span>O sistema não altera seu caixa físico.</span></div></div><p class="central-note-text">Use este painel como conferência das vendas digitais. Valores de abertura, sangria e despesas podem ser registrados no seu processo financeiro externo.</p></section>';
  }
  function loyalty(){
    var a=customers();
    function level(p){return p>=1000?'VIP':p>=500?'Ouro':p>=250?'Prata':'Bronze'}
    return centralHeader('🏆 Fidelidade','Visão de clientes e pontos estimados a partir das compras.')+
      '<section class="central-card"><div class="central-card-head"><div><b>Ranking de clientes</b><span>10 pontos a cada R$ 1 gasto</span></div><button class="btn" data-central="clientes">CRM</button></div><div class="central-table-wrap"><table class="central-table"><thead><tr><th>Cliente</th><th>Pedidos</th><th>Gasto</th><th>Pontos</th><th>Nível</th></tr></thead><tbody>'+(a.length?a.map(function(c){var pts=Math.floor(c.total*10);return '<tr><td><b>'+esc(c.name)+'</b><small>'+esc(c.phone||'')+'</small></td><td>'+c.orders+'</td><td>'+money(c.total)+'</td><td><b>'+pts.toLocaleString('pt-BR')+'</b></td><td><span class="selo acao">'+level(pts)+'</span></td></tr>'}).join(''):'<tr><td colspan="5"><div class="central-empty compact">Nenhum cliente encontrado.</div></td></tr>')+'</tbody></table></div></section>'+
      '<section class="central-card"><div class="central-card-head"><div><b>Regra sugerida</b><span>Personalize depois conforme sua estratégia.</span></div></div><p class="central-note-text">Os pontos exibidos são uma estimativa analítica e não são gravados no banco nesta versão. Isso evita alterar o saldo de clientes sem uma política de fidelidade definida.</p></section>';
  }
  function detail(){var o=C.detalhe,itens=C.detalheItens||[];return '<div class="central-detalhe"><div class="central-detail-head"><div><small>PEDIDO</small><h2>#'+esc(o.order_number)+'</h2><span>'+date(o.created_at)+'</span></div><button class="btn" data-central="fechar-detalhe">Fechar</button></div><div class="central-detail-grid"><div><b>Cliente</b><strong>'+esc(o.customer_name||'Cliente')+'</strong><span>'+esc(o.customer_phone||'—')+'</span></div><div><b>Tipo</b><strong>'+esc(o.order_type==='delivery'?'Entrega':'Retirada')+'</strong><span>'+esc(o.delivery_address||'Sem endereço')+'</span></div><div><b>Pagamento</b><strong>'+esc(o.payment_method||'—')+'</strong><span>'+esc(o.payment_change?('Troco para '+money(o.payment_change)):'')+'</span></div><div><b>Total</b><strong>'+money(o.total)+'</strong><span>Subtotal '+money(o.subtotal||o.total)+'</span></div></div><div class="central-status-edit"><b>Status</b><select id="central-detail-status" class="inp">'+STATUSES.filter(function(s){return s[0]!=='all'}).map(function(s){return '<option value="'+s[0]+'" '+(o.status===s[0]?'selected':'')+'>'+s[1]+'</option>'}).join('')+'</select><button class="btn primario" data-central="salvar-status">Salvar status</button></div><div class="central-items"><b>Itens do pedido</b>'+(itens.length?itens.map(function(i){return '<div><span>'+esc(i.quantity)+'× '+esc(i.product_name)+'</span><strong>'+money(i.line_total)+'</strong></div>'}).join(''):'<span>Nenhum item registrado.</span>')+'</div><div class="central-note"><b>Observações</b><p>'+esc(o.notes||'Nenhuma observação.')+'</p></div></div>';}
  function render(){if(C.page==='home'){injectNav();return}root.innerHTML='<div class="central-shell">'+(C.page==='dashboard'?dashboard():C.page==='pedidos'?pageOrders():C.page==='clientes'?pageCustomers():C.page==='cozinha'?kitchen():C.page==='caixa'?cash():C.page==='fidelidade'?loyalty():dashboard())+'</div>';}
  async function selectStore(id){if(C.realtime&&C.client){try{C.client.removeChannel(C.realtime)}catch(e){}C.realtime=null}if(C.autoRefresh){clearInterval(C.autoRefresh);C.autoRefresh=null}C._stores=C._stores.length?C._stores:await stores();C.loja=C._stores.find(function(l){return l.id===id})||C._stores[0]||null;C.client=clientFor(C.loja);C.session=null;C.orders=[];C.detalhe=null;C.detalheItens=[];render();if(!C.client){toast('Configure o Supabase nesta loja primeiro.');return}var s=await C.client.auth.getSession();C.session=s.data.session||null;if(C.session){await load();subscribeOrders();C.autoRefresh=setInterval(function(){if(C.session)load(true)},60000)}else loginModal();}
  function authError(e){var m=(e&&e.message||'').toLowerCase();if(m.includes('invalid login credentials'))return 'E-mail ou senha incorretos.';if(m.includes('email not confirmed'))return 'Confirme o e-mail da conta antes de entrar.';if(m.includes('too many requests'))return 'Muitas tentativas. Aguarde alguns minutos.';return e&&e.message||'Não foi possível entrar agora.';}
  async function login(){var email=document.getElementById('central-email').value.trim(),pass=document.getElementById('central-password').value,msg=document.getElementById('central-login-msg'),btn=document.getElementById('central-login-submit');if(!email){msg.textContent='Informe seu e-mail.';return}if(!pass){msg.textContent='Informe sua senha.';return}msg.textContent='Entrando…';btn.disabled=true;var r=await C.client.auth.signInWithPassword({email:email,password:pass});if(r.error){msg.textContent=authError(r.error);btn.disabled=false;return}C.session=r.data.session;document.getElementById('central-login').remove();await load();subscribeOrders();}
  async function signup(){var name=(document.getElementById('central-name')||{}).value||'',email=document.getElementById('central-email').value.trim(),pass=document.getElementById('central-password').value,confirm=document.getElementById('central-password-confirm').value,msg=document.getElementById('central-login-msg'),btn=document.getElementById('central-login-submit');if(!name.trim()){msg.textContent='Informe seu nome.';return}if(!email){msg.textContent='Informe seu e-mail.';return}if(pass.length<6){msg.textContent='A senha precisa ter pelo menos 6 caracteres.';return}if(pass!==confirm){msg.textContent='As senhas não conferem.';return}msg.textContent='Criando sua conta…';btn.disabled=true;var r=await C.client.auth.signUp({email:email,password:pass,options:{data:{full_name:name.trim()}}});if(r.error){msg.textContent=authError(r.error);btn.disabled=false;return}if(r.data.session){C.session=r.data.session;document.getElementById('central-login').remove();await load();subscribeOrders();return}msg.className='central-msg ok';msg.textContent='Cadastro criado. Confirme seu e-mail e aguarde o vínculo à loja.';btn.disabled=false;}
  function showAuthModal(mode){var old=document.getElementById('central-login');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',modalHtml(mode));var f=document.getElementById(mode==='signup'?'central-name':'central-email');if(f)f.focus();}
  async function resetPassword(){var email=document.getElementById('central-email').value.trim(),msg=document.getElementById('central-login-msg');if(!email){msg.textContent='Digite seu e-mail.';return}msg.textContent='Enviando…';var r=await C.client.auth.resetPasswordForEmail(email,{redirectTo:window.location.href.split('#')[0]});if(r.error){msg.textContent=authError(r.error);return}msg.className='central-msg ok';msg.textContent='Se o e-mail existir, você receberá as instruções.';}
  function togglePassword(){var i=document.getElementById('central-password'),b=document.querySelector('[data-central="toggle-password"]');if(!i||!b)return;var show=i.type==='password';i.type=show?'text':'password';b.textContent=show?'Ocultar':'Mostrar';}
  async function load(silent){if(!C.client||!C.session)return;C.loading=!silent;render();var r=await C.client.from('orders').select('*').eq('store_slug',C.loja.slug).order('created_at',{ascending:false}).limit(1000);C.loading=false;if(r.error){C.orders=[];C.loadError=r.error.message;render();showLoginOrError(r.error.message);return}C.orders=r.data||[];C.lastSync=new Date().toISOString();C.loadError=null;render();}
  function subscribeOrders(){if(!C.client||!C.session||!C.loja||!C.client.channel)return;C.realtime=C.client.channel('central-orders-'+C.loja.slug).on('postgres_changes',{event:'*',schema:'public',table:'orders',filter:'store_slug=eq.'+C.loja.slug},function(){load(true)}).subscribe(function(status){if(status==='CHANNEL_ERROR'){C.realtime=null;render();toast('Tempo real indisponível; atualização automática ativa.');}else if(status==='SUBSCRIBED'){render();}});}
  function showLoginOrError(msg){var el=document.createElement('div');el.className='central-modal-fundo';el.innerHTML='<div class="central-modal"><div class="central-modal-icon">⚠</div><h2>Acesso não autorizado</h2><p>A conta precisa estar vinculada a esta loja em <code>public.store_admins</code>.</p><p class="central-tech-error">'+esc(msg)+'</p><div class="acoes"><button class="btn primario" data-central="fechar-erro">Entendi</button></div></div></div>';document.body.appendChild(el);}
  function loginModal(){if(!C.client){toast('Configure o Supabase nesta loja primeiro.');return}showAuthModal('login');}
  async function openDetail(id){var o=C.orders.find(function(x){return x.id===id});if(!o)return;C.detalhe=o;C.detalheItens=[];render();if(!C.client)return;var r=await C.client.from('order_items').select('*').eq('order_id',id).order('created_at',{ascending:true});if(!r.error)C.detalheItens=r.data||[];render();}
  async function quickStatus(id,status){var o=C.orders.find(function(x){return x.id===id});if(!o||!C.client)return;var r=await C.client.from('orders').update({status:status,updated_at:new Date().toISOString()}).eq('id',id).eq('store_slug',C.loja.slug);if(r.error){toast('Não foi possível atualizar o pedido.');return}o.status=status;toast('Pedido #'+(o.order_number||'')+' atualizado.');render();}
  async function saveStatus(){var s=document.getElementById('central-detail-status').value,o=C.detalhe;if(!o||!C.client)return;var r=await C.client.from('orders').update({status:s,updated_at:new Date().toISOString()}).eq('id',o.id).eq('store_slug',C.loja.slug);if(r.error){toast('Não foi possível atualizar: '+r.error.message);return}o.status=s;toast('Status atualizado');render();}
  function csvCell(v){return '"'+String(v==null?'':v).replace(/"/g,'""')+'"';}
  function exportCSV(){var rows=activeOrders(),lines=[['Pedido','Cliente','Telefone','Tipo','Pagamento','Total','Status','Data'].map(csvCell).join(';')];rows.forEach(function(o){lines.push([o.order_number,o.customer_name,o.customer_phone,o.order_type==='delivery'?'Entrega':'Retirada',o.payment_method,o.total,statusLabel(o.status),date(o.created_at)].map(csvCell).join(';'))});var blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pedidos-'+(C.loja&&C.loja.slug||'loja')+'-'+dayKey(new Date())+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},500);toast('CSV exportado');}
  function goPage(p){C.page=p;C.busca='';C.status='all';render();if(C.loja&&!C.client)selectStore(C.loja.id);}
  document.addEventListener('click',function(e){var b=e.target.closest('[data-central]');if(!b)return;var a=b.dataset.central;
    if(a==='dashboard'||a==='pedidos'||a==='clientes'||a==='cozinha'||a==='caixa'||a==='fidelidade'){goPage(a);return}
    if(a==='period'){C.period=b.dataset.period||'all';render();return}
    if(a==='refresh'){load();return}
    if(a==='export-csv'){exportCSV();return}
    if(a==='fechar-login'){var x=document.getElementById('central-login');if(x)x.remove();return}
    if(a==='login'){login();return}if(a==='signup'){signup();return}if(a==='show-signup'){showAuthModal('signup');return}if(a==='show-login'){showAuthModal('login');return}if(a==='toggle-password'){togglePassword();return}if(a==='reset-password'){resetPassword();return}
    if(a==='logout'){if(C.realtime&&C.client){try{C.client.removeChannel(C.realtime)}catch(e){}C.realtime=null}if(C.autoRefresh)clearInterval(C.autoRefresh);if(C.client)C.client.auth.signOut();C.session=null;C.orders=[];render();loginModal();return}
    if(a==='quick-status'){quickStatus(b.dataset.id,b.dataset.status);return}if(a==='pedido'){openDetail(b.dataset.id);return}if(a==='fechar-detalhe'){C.detalhe=null;render();return}if(a==='salvar-status'){saveStatus();return}if(a==='fechar-erro'){var m=b.closest('.central-modal-fundo');if(m)m.remove();return}
  });
  document.addEventListener('change',function(e){if(e.target.id==='central-store'){selectStore(e.target.value);return}if(e.target.id==='central-status'){C.status=e.target.value;render();return}if(e.target.id==='central-period'){C.period=e.target.value;render();return}});
  document.addEventListener('input',function(e){if(e.target.id==='central-search'){C.busca=e.target.value;var pos=C.busca.length;render();var x=document.getElementById('central-search');if(x){x.focus();x.setSelectionRange(pos,pos)}}});
  document.addEventListener('keydown',function(e){if(e.key==='Enter'&&document.getElementById('central-login')){e.preventDefault();var b=document.getElementById('central-login-submit');if(b&&b.dataset.central==='signup')signup();else login();}});
  var obs=new MutationObserver(function(){injectNav()});obs.observe(root,{childList:true,subtree:false});window.__centralObserver=obs;
  window.addEventListener('hashchange',function(){if(location.hash==='#pedidos'){goPage('pedidos')}});
  stores().then(function(s){C._stores=s;injectNav();if(s.length){C.loja=s[0];C.client=clientFor(C.loja);var p=location.hash==='#pedidos'?'pedidos':'dashboard';C.page=p;render();selectStore(C.loja.id);}else injectNav();}).catch(function(){injectNav();});
})();
