/* Central de Operações — Admin Gerador.
   Front-end seguro: usa apenas a Publishable key do Supabase + RLS/store_admins. */
(function () {
  'use strict';
  var root = document.getElementById('raiz');
  if (!root) return;
  var DB_NAME = 'admin-gerador', STORE = 'lojas';
  var queryParams = new URLSearchParams(window.location.search);
  var DEV_EMAIL = 'rojonas71@gmail.com';
  var DEV_MODE = queryParams.get('area') === 'dev' || /^\/dev(?:\/admin\/admin\.html)?\/?$/.test(window.location.pathname);
  var OWNER_MODE = /^\/dono(?:\/index\.html)?\/?$/.test(window.location.pathname);
  var requested = queryParams.get('loja') || '';
  var PRIVATE_SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(requested) ? requested : '';
  var C = { page:'dashboard', loja:null, session:null, client:null, role:null, orders:[], loading:false, busca:'', status:'all', period:'all', detalhe:null, detalheItens:[], realtime:null, autoRefresh:null, _stores:[], storeHealth:{}, diagnosticsAt:null, lastSync:null, loadError:null };
  var STATUSES = [
    ['all','Todos'],['whatsapp_pending','Aguardando WhatsApp'],['received','Recebido'],['confirmed','Confirmado'],
    ['preparing','Em preparo'],['ready','Pronto'],['out_for_delivery','Saiu para entrega'],['completed','Concluído'],['cancelled','Cancelado']
  ];
  var PERIODS = [['all','Todo o período'],['today','Hoje'],['7d','Últimos 7 dias'],['30d','Últimos 30 dias']];
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function money(n){return (+n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
  function date(v){if(!v)return '—';var d=new Date(v);return d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});}
  function dayKey(v){var d=new Date(v);return isNaN(d)?'':d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  function idb(){return new Promise(function(ok,err){var r=indexedDB.open(DB_NAME,1);r.onsuccess=function(){ok(r.result)};r.onerror=function(){err(r.error)}})}
  function stores(){var list=Array.isArray(window.LOJAS)?window.LOJAS.slice():[];var base=window.LOJA;if(base&&base.slug&&base.supabase&&!list.some(function(x){return x.slug===base.slug}))list.unshift({nome:base.nome||base.slug,slug:base.slug,supabase:base.supabase});var seen={};list=list.filter(function(x){if(!x||!(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).test(x.slug||'')||seen[x.slug])return false;seen[x.slug]=true;x.id=x.slug;x.nome=x.nome||x.slug;return true});return Promise.resolve(list.sort(function(x,y){return (x.nome||'').localeCompare(y.nome||'')}))}
  function clientFor(l){if(!window.supabase||!window.supabase.createClient)return null;if(!l||!l.supabase||!l.supabase.enabled||!l.supabase.url||!l.supabase.publishableKey)return null;return window.supabase.createClient(l.supabase.url,l.supabase.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'admin-central-'+(l.slug||'loja')}})}
  function toast(t){var e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.appendChild(e)}e.textContent=t;clearTimeout(window.__centralToast);window.__centralToast=setTimeout(function(){e.remove()},3000)}
  function filteredPeriod(list){var now=Date.now(),ms=C.period==='today'?86400000:C.period==='7d'?7*86400000:C.period==='30d'?30*86400000:0;if(!ms)return list;return list.filter(function(o){var t=new Date(o.created_at).getTime();return t>=now-ms});}
  function activeOrders(){return filteredPeriod(C.orders||[]);}
  function statusLabel(s){var x=STATUSES.find(function(a){return a[0]===s});return x?x[1]:s||'Sem status';}
  function statusClass(s){return s==='completed'?'ok':s==='cancelled'?'erro':s==='preparing'||s==='ready'||s==='out_for_delivery'?'acao':'aviso';}
  function modalHtml(mode){
    mode=mode||'login';if(DEV_MODE)mode='login';var cadastro=mode==='signup';
    var titulo=DEV_MODE?'Entrar na Área do Desenvolvedor':OWNER_MODE?'Entrar na Área do Dono':(cadastro?'Criar acesso administrativo':'Entrar na Central');
    var descricao=DEV_MODE?'Área restrita à conta autorizada. O login é validado pelo Supabase Auth.':OWNER_MODE?'Acesse somente a loja vinculada à sua conta. O link não substitui as permissões do Supabase.':(cadastro?'Crie sua conta para solicitar acesso à operação da ':'Acesse a operação da ')+'<b>'+esc(C.loja&&C.loja.nome||'loja selecionada')+'</b>.';
    var emailField='<label>E-mail<input id="central-email" class="inp" type="email" autocomplete="email" placeholder="admin@empresa.com" '+(DEV_MODE?'value="'+esc(DEV_EMAIL)+'" readonly':'')+'></label>';
    var authLinks=(DEV_MODE||OWNER_MODE)?'<div class="central-login-options"><button type="button" class="link-btn" data-central="reset-password">Esqueci minha senha</button><span>Supabase Auth</span></div>':'<div class="central-login-options">'+(cadastro?'<button type="button" class="link-btn" data-central="show-login">Já tenho uma conta</button>':'<div><button type="button" class="link-btn" data-central="reset-password">Esqueci minha senha</button> · <button type="button" class="link-btn" data-central="show-signup">Criar cadastro</button></div>')+'<span>Supabase Auth</span></div>';
    return '<div class="central-modal-fundo" id="central-login"><div class="central-modal central-login-modal"><div class="central-modal-icon">'+(cadastro?'👤':'🔐')+'</div><div><h2>'+titulo+'</h2><p>'+descricao+'</p></div>'+(cadastro?'<label>Nome<input id="central-name" class="inp" type="text" autocomplete="name" placeholder="Seu nome"></label>':'')+emailField+'<label>Senha<div class="central-password-wrap"><input id="central-password" class="inp" type="password" autocomplete="'+(cadastro?'new-password':'current-password')+'" placeholder="'+(cadastro?'Mínimo de 6 caracteres':'Sua senha')+'"><button type="button" class="central-password-toggle" data-central="toggle-password">Mostrar</button></div></label>'+(cadastro?'<label>Confirmar senha<input id="central-password-confirm" class="inp" type="password" autocomplete="new-password" placeholder="Repita sua senha"></label>':'')+authLinks+'<div id="central-login-msg" class="central-msg"></div><div class="acoes central-login-actions"><button class="btn" data-central="fechar-login">Cancelar</button><button class="btn primario" id="central-login-submit" data-central="'+(cadastro?'signup':'login')+'">'+(cadastro?'Criar cadastro':'Entrar')+'</button></div><small>'+(DEV_MODE?'Acesso à interface de diagnóstico. Não concede privilégios administrativos no banco nem acesso a pedidos.':OWNER_MODE?'O acesso exige login e o papel owner para esta loja em public.store_admins.':cadastro?'O cadastro não libera acesso automaticamente. Um administrador precisa vincular sua conta à loja em <code>public.store_admins</code>.':'O acesso é controlado pelo Supabase e pelas políticas RLS.')+'</small></div></div>';
  }
  function injectNav(){
    if(DEV_MODE||OWNER_MODE)return;
    var topo=root.querySelector('.topo-lista');if(!topo||root.querySelector('.central-nav'))return;
    var nav=document.createElement('div');nav.className='central-nav';nav.innerHTML='<div class="central-brand"><b>Central</b><span>Operação multi-lojas</span></div><div class="central-links"><button data-central="dashboard">📊 Visão geral</button><button data-central="pedidos">🛒 Pedidos</button><button data-central="clientes">👥 Clientes</button><button data-central="owner">👑 Área do Dono</button><button data-central="dev">🧑‍💻 Área do Dev</button></div>';
    topo.parentNode.insertBefore(nav,topo);
  }
  function centralHeader(title,sub){var opts=PRIVATE_SLUG?(C.loja?[C.loja]:[]):(C._stores||[]);return '<div class="central-header"><div><small>'+(DEV_MODE?'JONASH.DEV · ÁREA RESTRITA':OWNER_MODE?'ÁREA PRIVADA DO PROPRIETÁRIO':'ADMIN GERADOR · CENTRAL')+'</small><h1>'+title+'</h1><p>'+sub+'</p></div><div class="central-head-actions">'+(DEV_MODE||OWNER_MODE?'':'<select id="central-store" class="inp" '+(PRIVATE_SLUG?'disabled title="Loja fixada pelo link privado"':'')+'>'+opts.map(function(l){return '<option value="'+esc(l.id)+'" '+(C.loja&&C.loja.id===l.id?'selected':'')+'>'+esc(l.nome)+' · '+esc(l.slug)+'</option>'}).join('')+'</select>')+'<span class="central-live '+(C.realtime?'on':'')+'"><i></i>'+(C.realtime?'Tempo real':'Atualização manual')+'</span><button class="btn fantasma" data-central="logout">Sair</button></div></div>'; }
  function metrics(o){var total=o.reduce(function(s,x){return s+(+x.total||0)},0),open=o.filter(function(x){return !['completed','cancelled'].includes(x.status)}).length,done=o.filter(function(x){return x.status==='completed'}).length,customers=uniqueCustomers(o).length,avg=o.length?total/o.length:0,rate=o.length?Math.round(done/o.length*100):0;return '<div class="central-metrics"><div><b>'+o.length+'</b><span>Pedidos</span><small>no período</small></div><div><b>'+money(total)+'</b><span>Faturamento</span><small>valor bruto</small></div><div><b>'+money(avg)+'</b><span>Ticket médio</span><small>por pedido</small></div><div><b>'+open+'</b><span>Em aberto</span><small>aguardando ação</small></div><div><b>'+customers+'</b><span>Clientes</span><small>identificados</small></div><div><b>'+rate+'%</b><span>Conclusão</span><small>'+done+' concluídos</small></div></div>';}
  function uniqueCustomers(o){var m={};o.forEach(function(x){var k=(x.customer_phone||x.customer_name||'').trim().toLowerCase();if(k)m[k]=1});return Object.keys(m);}
  function dashboard(){
    var o=activeOrders(),total=o.reduce(function(s,x){return s+(+x.total||0)},0),open=o.filter(function(x){return !['completed','cancelled'].includes(x.status)}),statusCounts={};o.forEach(function(x){statusCounts[x.status]=(statusCounts[x.status]||0)+1});
    var recent=o.slice().sort(function(a,b){return new Date(b.created_at)-new Date(a.created_at)}).slice(0,6);
    var top=o.slice().sort(function(a,b){return (+b.total||0)-(+a.total||0)}).slice(0,5);
    var byDay={};o.forEach(function(x){var k=dayKey(x.created_at);if(k)byDay[k]=(byDay[k]||0)+(+x.total||0)});var days=Object.keys(byDay).sort().slice(-7),maxDay=Math.max.apply(Math,days.map(function(k){return byDay[k]}).concat([1]));
    var bestCustomer=customers().slice(0,5),sync=C.lastSync?date(C.lastSync):'Ainda não sincronizado';
    return centralHeader('📊 Visão geral','Acompanhe a operação, pedidos, clientes e desempenho da loja.')+
      '<div class="central-period"><div><b>Período</b><span>Indicadores da operação</span></div><div class="central-period-actions">'+PERIODS.map(function(p){return '<button class="btn '+(C.period===p[0]?'primario':'')+'" data-central="period" data-period="'+p[0]+'">'+p[1]+'</button>'}).join('')+'</div></div>'+metrics(o)+
      '<div class="central-grid-2"><section class="central-card"><div class="central-card-head"><div><b>Pedidos por status</b><span>Distribuição no período selecionado</span></div><button class="btn" data-central="pedidos">Ver pedidos</button></div><div class="status-resumo">'+STATUSES.slice(1).map(function(s){return '<div><span><i class="dot '+statusClass(s[0])+'"></i>'+s[1]+'</span><b>'+((statusCounts[s[0]]||0))+'</b></div>'}).join('')+'</div></section><section class="central-card"><div class="central-card-head"><div><b>Saúde da loja</b><span>Conectividade e operação</span></div></div><div class="saude-lista"><div><span>Supabase</span><b class="'+(C.client?'saude-ok':'saude-erro')+'">'+(C.client?'Configurado':'Não configurado')+'</b></div><div><span>Autenticação</span><b class="'+(C.session?'saude-ok':'saude-aviso')+'">'+(C.session?'Conectado':'Não conectado')+'</b></div><div><span>Tempo real</span><b class="'+(C.realtime?'saude-ok':'saude-aviso')+'">'+(C.realtime?'Ativo':'Indisponível')+'</b></div><div><span>Pedidos carregados</span><b>'+C.orders.length+'</b></div></div></section></div>'+
      '<div class="central-card central-performance"><div class="central-card-head"><div><b>Desempenho dos últimos dias</b><span>Faturamento por dia no período selecionado</span></div><span class="central-sync">Sincronizado '+esc(sync)+'</span></div><div class="central-bars">'+(days.length?days.map(function(k){var d=new Date(k+'T12:00:00');return '<div class="central-bar-col"><span>'+money(byDay[k])+'</span><div class="central-bar" style="height:'+Math.max(8,Math.round(byDay[k]/maxDay*110))+'px"></div><small>'+d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})+'</small></div>'}).join(''):'<div class="central-empty compact"><b>Sem dados de faturamento.</b></div>')+'</div></section><section class="central-card"><div class="central-card-head"><div><b>Clientes de maior valor</b><span>Relacionamento no período</span></div><button class="btn" data-central="clientes">Ver clientes</button></div><div class="recent-list">'+(bestCustomer.length?bestCustomer.map(function(c){return '<div class="customer-mini"><span><b>'+esc(c.name)+'</b><small>'+esc(c.phone||'Sem telefone')+' · '+c.orders+' pedido(s)</small></span><strong>'+money(c.total)+'</strong></div>'}).join(''):'<div class="central-empty compact"><b>Nenhum cliente.</b></div>')+'</div></section></div>'+
      '<div class="central-grid-2"><section class="central-card"><div class="central-card-head"><div><b>Pedidos recentes</b><span>Últimas movimentações</span></div><button class="btn" data-central="refresh">↻ Atualizar</button></div><div class="recent-list">'+(recent.length?recent.map(function(x){return '<button class="recent-row" data-central="pedido" data-id="'+esc(x.id)+'"><span><b>#'+esc(x.order_number)+'</b><small>'+esc(x.customer_name||'Cliente')+' · '+date(x.created_at)+'</small></span><strong>'+money(x.total)+'</strong><i class="selo '+statusClass(x.status)+'">'+esc(statusLabel(x.status))+'</i></button>'}).join(''):'<div class="central-empty compact"><b>Nenhum pedido no período.</b></div>')+'</div></section><section class="central-card"><div class="central-card-head"><div><b>Maiores pedidos</b><span>Por valor</span></div></div><div class="recent-list">'+(top.length?top.map(function(x){return '<button class="recent-row" data-central="pedido" data-id="'+esc(x.id)+'"><span><b>#'+esc(x.order_number)+'</b><small>'+esc(x.customer_name||'Cliente')+'</small></span><strong>'+money(x.total)+'</strong></button>'}).join(''):'<div class="central-empty compact"><b>Nenhum pedido.</b></div>')+'</div></section></div>'+
      '<div class="central-actions-bar"><button class="btn primario" data-central="pedidos">🛒 Gerenciar pedidos</button><button class="btn" data-central="clientes">👥 Ver clientes</button><button class="btn" data-central="export-csv">⬇ Exportar CSV</button></div>';
  }
  function filtered(){var q=(C.busca||'').toLowerCase();return activeOrders().filter(function(o){if(C.status&&C.status!=='all'&&o.status!==C.status)return false;if(!q)return true;return [o.order_number,o.customer_name,o.customer_phone,o.delivery_address,o.payment_method,o.status].join(' ').toLowerCase().includes(q)});}
  function ordersTable(){var a=filtered();if(C.loading)return '<div class="central-empty"><b>Carregando pedidos…</b><span>Consultando o Supabase com as permissões da loja.</span></div>';if(!a.length)return '<div class="central-empty"><div>🛒</div><b>Nenhum pedido encontrado</b><span>Ajuste a busca, status ou período.</span></div>';return '<div class="central-table-wrap"><table class="central-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Tipo</th><th>Pagamento</th><th>Total</th><th>Status</th><th>Data</th></tr></thead><tbody>'+a.map(function(o){return '<tr data-central="pedido" data-id="'+esc(o.id)+'"><td><b>#'+esc(o.order_number)+'</b></td><td><b>'+esc(o.customer_name||'Cliente')+'</b><small>'+esc(o.customer_phone||'')+'</small></td><td>'+esc(o.order_type==='delivery'?'Entrega':'Retirada')+'</td><td>'+esc(o.payment_method||'—')+'</td><td><b>'+money(o.total)+'</b></td><td><span class="selo '+statusClass(o.status)+'">'+esc(statusLabel(o.status))+'</span></td><td>'+date(o.created_at)+'</td></tr>'}).join('')+'</tbody></table></div>';}
  function pageOrders(){return centralHeader('🛒 Pedidos','Controle o fluxo de pedidos em tempo real.')+metrics(activeOrders())+'<div class="central-toolbar"><input id="central-search" class="inp" placeholder="Buscar pedido, cliente, telefone…" value="'+esc(C.busca)+'"><select id="central-status" class="inp">'+STATUSES.map(function(s){return '<option value="'+s[0]+'" '+(C.status===s[0]?'selected':'')+'>'+s[1]+'</option>'}).join('')+'</select><select id="central-period" class="inp">'+PERIODS.map(function(p){return '<option value="'+p[0]+'" '+(C.period===p[0]?'selected':'')+'>'+p[1]+'</option>'}).join('')+'</select><button class="btn" data-central="refresh">↻ Atualizar</button><button class="btn" data-central="export-csv">⬇ CSV</button><span class="central-user">● '+esc(C.session&&C.session.user&&C.session.user.email||'Administrador')+'</span></div>'+ordersTable()+(C.detalhe?detail():'');}
  function customers(){var map={};activeOrders().forEach(function(o){var k=(o.customer_phone||o.customer_name||'').trim().toLowerCase();if(!k)return;if(!map[k])map[k]={name:o.customer_name||'Cliente',phone:o.customer_phone||'',orders:0,total:0,last:o.created_at};map[k].orders++;map[k].total+=(+o.total||0);if(new Date(o.created_at)>new Date(map[k].last))map[k].last=o.created_at});return Object.keys(map).map(function(k){return map[k]}).sort(function(a,b){return b.total-a.total});}
  function pageCustomers(){var a=customers(),q=(C.busca||'').toLowerCase();if(q)a=a.filter(function(c){return (c.name+' '+c.phone).toLowerCase().includes(q)});return centralHeader('👥 Clientes','Base de clientes formada pelos pedidos da loja.')+'<div class="central-toolbar"><input id="central-search" class="inp" placeholder="Buscar cliente ou telefone…" value="'+esc(C.busca)+'"><select id="central-period" class="inp">'+PERIODS.map(function(p){return '<option value="'+p[0]+'" '+(C.period===p[0]?'selected':'')+'>'+p[1]+'</option>'}).join('')+'</select><button class="btn" data-central="refresh">↻ Atualizar</button><button class="btn" data-central="export-csv">⬇ CSV</button></div><div class="central-metrics"><div><b>'+a.length+'</b><span>Clientes</span></div><div><b>'+money(a.reduce(function(s,c){return s+c.total},0))+'</b><span>Faturamento</span></div><div><b>'+((a.reduce(function(s,c){return s+c.orders},0)/Math.max(a.length,1)).toFixed(1))+'</b><span>Pedidos por cliente</span></div><div><b>'+money(a.length?a.reduce(function(s,c){return s+c.total},0)/a.length:0)+'</b><span>Valor médio/cliente</span></div></div><div class="central-table-wrap"><table class="central-table"><thead><tr><th>Cliente</th><th>Telefone</th><th>Pedidos</th><th>Total</th><th>Último pedido</th></tr></thead><tbody>'+(a.length?a.map(function(c){return '<tr><td><b>'+esc(c.name)+'</b></td><td>'+esc(c.phone||'—')+'</td><td>'+c.orders+'</td><td><b>'+money(c.total)+'</b></td><td>'+date(c.last)+'</td></tr>'}).join(''):'<tr><td colspan="5"><div class="central-empty compact"><b>Nenhum cliente encontrado.</b></div></td></tr>')+'</tbody></table></div>';}
  function detail(){var o=C.detalhe,itens=C.detalheItens||[];return '<div class="central-detalhe"><div class="central-detail-head"><div><small>PEDIDO</small><h2>#'+esc(o.order_number)+'</h2><span>'+date(o.created_at)+'</span></div><button class="btn" data-central="fechar-detalhe">Fechar</button></div><div class="central-detail-grid"><div><b>Cliente</b><strong>'+esc(o.customer_name||'Cliente')+'</strong><span>'+esc(o.customer_phone||'—')+'</span></div><div><b>Tipo</b><strong>'+esc(o.order_type==='delivery'?'Entrega':'Retirada')+'</strong><span>'+esc(o.delivery_address||'Sem endereço')+'</span></div><div><b>Pagamento</b><strong>'+esc(o.payment_method||'—')+'</strong><span>'+esc(o.payment_change?('Troco para '+money(o.payment_change)):'')+'</span></div><div><b>Total</b><strong>'+money(o.total)+'</strong><span>Subtotal '+money(o.subtotal||o.total)+'</span></div></div><div class="central-status-edit"><b>Status</b><select id="central-detail-status" class="inp">'+STATUSES.filter(function(s){return s[0]!=='all'}).map(function(s){return '<option value="'+s[0]+'" '+(o.status===s[0]?'selected':'')+'>'+s[1]+'</option>'}).join('')+'</select><button class="btn primario" data-central="salvar-status">Salvar status</button></div><div class="central-items"><b>Itens do pedido</b>'+(itens.length?itens.map(function(i){return '<div><span>'+esc(i.quantity)+'× '+esc(i.product_name)+'</span><strong>'+money(i.line_total)+'</strong></div>'}).join(''):'<span>Nenhum item registrado.</span>')+'</div><div class="central-note"><b>Observações</b><p>'+esc(o.notes||'Nenhuma observação.')+'</p></div></div>';}
  function storeConfigIssues(l, all){
    var issues=[];
    if(!l) return ['Cadastro vazio'];
    if(!String(l.nome||'').trim())issues.push('Nome da loja vazio');
    if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(String(l.slug||'')))issues.push('Slug inválido: use letras minúsculas, números e hífen');
    if(!l.supabase)issues.push('Configuração Supabase ausente');
    else{
      if(!l.supabase.enabled)issues.push('Supabase desativado');
      if(!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(String(l.supabase.url||'')))issues.push('URL Supabase ausente ou inválida');
      if(!String(l.supabase.publishableKey||'').trim())issues.push('Publishable key ausente');
      if(/service_role|secret/i.test(String(l.supabase.publishableKey||'')))issues.push('Chave suspeita: nunca use service_role no frontend');
    }
    var duplicates=(all||[]).filter(function(x){return x&&x.slug&&x.slug===l.slug}).length;
    if(duplicates>1)issues.push('Slug duplicado no cadastro local');
    return issues;
  }
  async function checkStoreHealth(l){
    var issues=storeConfigIssues(l,C._stores),result={slug:l&&l.slug,status:'attention',issues:issues.slice(),checkedAt:new Date().toISOString(),connection:'Não testada'};
    if(issues.length){result.status='error';result.connection='Configuração incompleta';return result}
    if(navigator.onLine===false){result.status='attention';result.connection='Dispositivo offline';result.issues.push('Conecte-se à internet e execute o diagnóstico novamente.');return result}
    try{
      var url=String(l.supabase.url).replace(/\/$/,''),key=String(l.supabase.publishableKey);
      var controller=typeof AbortController!=='undefined'?new AbortController():null;
      var timeout=controller?setTimeout(function(){controller.abort()},8000):null;
      var response=await fetch(url+'/auth/v1/health',{method:'GET',headers:{'apikey':key},signal:controller?controller.signal:undefined,cache:'no-store'});
      if(timeout)clearTimeout(timeout);
      if(response.ok){result.status='ok';result.connection='Serviço Auth respondeu';result.issues=[]}
      else{result.status='error';result.connection='HTTP '+response.status;result.issues.push(response.status===401||response.status===403?'A chave pública pode estar incorreta ou não ser aceita por este projeto.':'O Supabase respondeu com erro; confira URL, chave e estado do projeto.');}
    }catch(e){result.status='error';result.connection=e&&e.name==='AbortError'?'Tempo esgotado':'Falha de rede/CORS';result.issues.push('Confira a URL do projeto, a publishable key, internet e se o projeto Supabase está ativo.');}
    return result;
  }
  async function runStoreDiagnostics(){
    var list=(C._stores||[]).slice();
    C.storeHealth={};
    await Promise.all(list.map(async function(l){var r=await checkStoreHealth(l);C.storeHealth[l.slug||l.id||'sem-slug']=r}));
    C.diagnosticsAt=new Date().toISOString();
    render();
  }
  function pageDev(){
    var supa=!!(C.client),auth=!!(C.session),realtime=!!(C.realtime),online=navigator.onLine!==false;
    var list=(C._stores||[]).slice(),health=C.storeHealth||{};
    var checks=[['Navegador online',online],['Loja selecionada',!!C.loja],['Supabase configurado',supa],['Sessão da Área Dev',auth&&isDevUser()],['Catálogo local de lojas carregado',Array.isArray(C._stores)],['Diagnóstico por loja executado',!!C.diagnosticsAt]];
    function item(x){return '<div class="central-dev-check"><span>'+x[0]+'</span><b class="'+(x[1]?'saude-ok':'saude-aviso')+'">'+(x[1]?'OK':'Atenção')+'</b></div>';}
    function storeRow(l,i){var h=health[l.slug||l.id||'sem-slug'],issues=storeConfigIssues(l,list),status=h?h.status:(issues.length?'error':'pending'),label=status==='ok'?'Conexão OK':status==='error'?'Erro encontrado':status==='attention'?'Verificar':'Aguardando teste',cls=status==='ok'?'saude-ok':status==='error'?'saude-erro':'saude-aviso',issueText=h&&h.issues.length?h.issues.join(' • '):issues.length?issues.join(' • '):h?h.connection:'Clique em “Testar todas” para validar a resposta do Auth.';
      return '<tr><td><b>'+esc(l.nome||'Sem nome')+'</b><small class="dev-store-meta">'+esc(l.slug||'sem slug')+'</small></td><td><span class="'+cls+'">'+label+'</span><small class="dev-store-meta">'+esc(h&&h.connection||'Ainda não testado')+'</small></td><td><small>'+esc(issueText)+'</small></td><td><button class="btn" data-central="dev-owner-link" data-slug="'+esc(l.slug||'')+'">Copiar link do dono</button> <button class="btn" data-central="dev-store-help" data-slug="'+esc(l.slug||'')+'">Como corrigir</button></td></tr>';
    }
    var okCount=list.filter(function(l){return health[l.slug||l.id||'sem-slug']&&health[l.slug||l.id||'sem-slug'].status==='ok'}).length;
    var badCount=list.filter(function(l){var h=health[l.slug||l.id||'sem-slug'];return h?h.status!=='ok':storeConfigIssues(l,list).length>0}).length;
    var storeTable='<section class="central-card dev-stores-card"><div class="central-card-head"><div><b>🏪 Lojas configuradas para links individuais</b><span>'+list.length+' loja(s) · '+okCount+' conexão(ões) OK · '+badCount+' com atenção/erro</span></div><button class="btn primario" data-central="dev-refresh">🩺 Testar todas</button></div><p class="dev-disclaimer">A lista vem de config/lojas.js (catálogo de configurações publicado). Cadastre cada loja ali para que o link funcione em qualquer dispositivo. O teste consulta apenas o endpoint de saúde do Auth; não lê pedidos, clientes nem confirma políticas RLS.</p><div class="central-table-wrap"><table class="central-table dev-stores-table"><thead><tr><th>Loja / slug</th><th>Diagnóstico</th><th>Possível erro / resultado</th><th>Ação</th></tr></thead><tbody>'+(list.length?list.map(storeRow).join(''):'<tr><td colspan="4">Nenhuma loja configurada. Confira config/loja.js e config/lojas.js.</td></tr>')+'</tbody></table></div><div class="dev-diagnostic-footer">'+(C.diagnosticsAt?'Último teste: '+esc(date(C.diagnosticsAt)):'Nenhum teste executado ainda')+' · <button class="link-btn" data-central="dev-copy">Copiar relatório seguro</button></div></section>';
    return centralHeader('🧑‍💻 Área do Desenvolvedor','Painel técnico multi-lojas para identificar falhas de configuração e orientar a correção.')+
      '<div class="central-card"><div class="central-card-head"><div><b>Estado do sistema</b><span>Diagnóstico técnico sem carregar pedidos ou dados pessoais de clientes.</span></div><button class="btn" data-central="dev-refresh">↻ Atualizar diagnóstico</button></div><div class="central-dev-list">'+checks.map(item).join('')+'</div></div>'+storeTable+
      (DEV_MODE?'<section class="central-card"><div class="central-card-head"><div><b>Conta autorizada</b><span>Identidade autenticada pelo Supabase Auth</span></div></div><div class="saude-lista"><div><span>E-mail permitido</span><b>'+esc(DEV_EMAIL)+'</b></div><div><span>E-mail da sessão</span><b>'+esc(C.session&&C.session.user&&C.session.user.email||'—')+'</b></div><div><span>Rota</span><b>/dev/</b></div></div></section>':'')+'<div class="central-grid-2"><section class="central-card"><div class="central-card-head"><div><b>Ambiente</b><span>Informações não sensíveis</span></div></div><div class="saude-lista"><div><span>Versão</span><b>V9.2</b></div><div><span>Lojas listadas</span><b>'+list.length+'</b></div><div><span>Loja atual</span><b>'+esc(C.loja&&C.loja.nome||'Não selecionada')+'</b></div><div><span>Host</span><b>'+esc(location.host||'local')+'</b></div><div><span>Conexão</span><b>'+(online?'Online':'Offline')+'</b></div></div></section><section class="central-card"><div class="central-card-head"><div><b>Guia de correção</b><span>Passos recomendados quando uma loja falhar</span></div></div><ol class="central-dev-tips"><li>Abra <code>config/lojas.js</code> e cadastre cada dono com nome, slug e configuração Supabase individual.</li><li>Confira a loja principal em <code>config/loja.js</code> e a configuração correspondente no catálogo.</li><li>Confirme que a URL e a chave pertencem ao mesmo projeto Supabase.</li><li>Veja se o projeto Supabase está ativo e se Auth está habilitado.</li><li>Para erro de login/permissão, verifique <code>public.store_admins</code> e as políticas RLS no painel Supabase.</li><li>Nunca coloque <code>service_role</code> no frontend e não desative RLS para “resolver” erro.</li></ol><button class="btn" data-central="dev-copy">📋 Copiar resumo seguro</button></section></div>';
  }
  function ownerPage(){
    if(C.role!=='owner')return centralHeader('🔒 Área do Dono','Acesso restrito ao proprietário vinculado à loja.')+'<section class="central-card"><h3>Acesso restrito</h3><p>Esta área exige o papel <code>owner</code> em <code>public.store_admins</code> para a loja selecionada.</p></section>';
    var o=activeOrders(),gross=o.reduce(function(a,x){return a+(+x.total||0)},0),done=o.filter(function(x){return x.status==='completed'}),cancel=o.filter(function(x){return x.status==='cancelled'}),valid=o.filter(function(x){return x.status!=='cancelled'}),net=valid.reduce(function(a,x){return a+(+x.total||0)},0),avg=valid.length?net/valid.length:0;
    var pending=o.filter(function(x){return !['completed','cancelled'].includes(x.status)}).length;
    return centralHeader('👑 Área do Dono','Visão executiva e indicadores da loja, com acesso exclusivo ao proprietário.')+
      '<div class="central-period"><div><b>Resumo do negócio</b><span>Valores estimados com base nos pedidos carregados</span></div><div class="central-period-actions">'+PERIODS.map(function(p){return '<button class="btn '+(C.period===p[0]?'primario':'')+'" data-central="period" data-period="'+p[0]+'">'+p[1]+'</button>'}).join('')+'</div></div>'+
      '<div class="central-metrics"><div><b>'+money(gross)+'</b><span>Valor bruto</span><small>inclui cancelados</small></div><div><b>'+money(net)+'</b><span>Pedidos não cancelados</span><small>não representa lucro líquido</small></div><div><b>'+money(avg)+'</b><span>Ticket médio</span><small>sem cancelados</small></div><div><b>'+o.length+'</b><span>Pedidos</span><small>no período</small></div><div><b>'+pending+'</b><span>Em andamento</span><small>precisam de atenção</small></div><div><b>'+cancel.length+'</b><span>Cancelados</span><small>'+ (o.length?Math.round(cancel.length/o.length*100):0)+'% dos pedidos</small></div></div>'+
      '<section class="central-card"><div class="central-card-head"><div><b>🔗 Link privado do proprietário</b><span>O link abre diretamente esta loja; login e RLS continuam obrigatórios.</span></div></div><div class="central-toolbar"><input class="inp" id="central-private-link" readonly value="'+esc(privateLink())+'"><button class="btn primario" data-central="copy-private-link">Copiar link privado</button></div><p class="central-muted">Compartilhe apenas com o proprietário autorizado. Para cada loja, use um slug único e vincule o e-mail do dono no Supabase.</p></section>'+
      '<div class="central-grid-2"><section class="central-card"><div class="central-card-head"><div><b>Gestão da loja</b><span>Contexto do negócio</span></div></div><div class="saude-lista"><div><span>Loja</span><b>'+esc(C.loja&&C.loja.nome||'—')+'</b></div><div><span>Identificador</span><b>'+esc(C.loja&&C.loja.slug||'—')+'</b></div><div><span>Seu papel</span><b class="saude-ok">Proprietário</b></div><div><span>Última sincronização</span><b>'+esc(C.lastSync?date(C.lastSync):'Ainda não sincronizado')+'</b></div></div><p class="central-muted">Indicadores calculados apenas sobre os pedidos que a Central carregou (limite atual de 1.000). Custos, taxas e despesas não estão incluídos no lucro.</p></section><section class="central-card"><div class="central-card-head"><div><b>Ações rápidas</b><span>Acompanhe a operação</span></div></div><div class="central-period-actions"><button class="btn primario" data-central="pedidos">🛒 Gerenciar pedidos</button><button class="btn" data-central="clientes">👥 Ver clientes</button><button class="btn" data-central="refresh">↻ Atualizar indicadores</button><button class="btn" data-central="export-csv">⬇ Exportar CSV</button></div></section></div>'+
      '<section class="central-card"><div class="central-card-head"><div><b>Pedidos recentes</b><span>Últimas movimentações do período</span></div><button class="btn" data-central="pedidos">Ver todos</button></div><div class="recent-list">'+(o.slice().sort(function(a,b){return new Date(b.created_at)-new Date(a.created_at)}).slice(0,6).map(function(x){return '<button class="recent-row" data-central="pedido" data-id="'+esc(x.id)+'"><span><b>#'+esc(x.order_number)+'</b><small>'+esc(x.customer_name||'Cliente')+' · '+date(x.created_at)+'</small></span><strong>'+money(x.total)+'</strong><i class="selo '+statusClass(x.status)+'">'+esc(statusLabel(x.status))+'</i></button>'}).join('')||'<div class="central-empty compact"><b>Nenhum pedido neste período.</b></div>')+'</div></section>';
  }
  function isDevUser(){return !!(C.session&&C.session.user&&String(C.session.user.email||'').toLowerCase()===DEV_EMAIL.toLowerCase());}
  function deniedDevPage(){return '<section class="central-card" style="max-width:680px;margin:8vh auto;padding:28px"><div class="central-modal-icon">🔒</div><h1>Acesso restrito</h1><p>A Área do Desenvolvedor está disponível somente para a conta autorizada.</p><p>Entre com <code>'+esc(DEV_EMAIL)+'</code>. Nenhum pedido ou dado de cliente foi carregado.</p><div class="acoes"><button class="btn primario" data-central="logout">Sair da conta</button></div></section>'; }
  function render(){if(C.page==='home'){injectNav();return}if(DEV_MODE&&!C.session){root.innerHTML='<div class="central-shell"><section class="central-card" style="max-width:680px;margin:8vh auto;padding:28px"><h1>🔐 Autenticação necessária</h1><p>Entre com a conta autorizada para abrir a Área do Desenvolvedor.</p><p>Nenhum pedido ou dado de cliente é carregado nesta rota.</p></section></div>';return}if(DEV_MODE&&C.session&&!isDevUser())C.page='denied-dev';if(C.page==='owner'&&C.role!=='owner'){C.page='owner'}root.innerHTML='<div class="central-shell">'+(C.page==='dashboard'?dashboard():C.page==='pedidos'?pageOrders():C.page==='clientes'?pageCustomers():C.page==='dev'?pageDev():C.page==='owner'?ownerPage():C.page==='denied'?deniedPage():C.page==='denied-dev'?deniedDevPage():dashboard())+'</div>'; }
  async function loadRole(){C.role=null;if(!C.client||!C.session||!C.loja)return;try{var r=await C.client.from('store_admins').select('role').eq('user_id',C.session.user.id).eq('store_slug',C.loja.slug).maybeSingle();if(!r.error&&r.data)C.role=r.data.role||null;}catch(e){C.role=null}}
  function deniedPage(){return '<section class="central-card" style="max-width:680px;margin:8vh auto;padding:28px"><div class="central-modal-icon">🔒</div><h1>Acesso não autorizado</h1><p>Esta conta não está vinculada à loja <b>'+esc(C.loja&&C.loja.slug||PRIVATE_SLUG||'selecionada')+'</b>. Nenhum pedido ou cliente foi carregado.</p><p>Peça ao administrador para vincular seu e-mail à loja em <code>public.store_admins</code>. O link sozinho não concede permissão.</p><div class="acoes"><button class="btn primario" data-central="logout">Sair da conta</button></div></section>'; }
  function privateLink(){var slug=C.loja&&C.loja.slug||'';return location.origin+'/dono/?loja='+encodeURIComponent(slug)}
  async function selectStore(id){if(C.realtime&&C.client){try{C.client.removeChannel(C.realtime)}catch(e){}C.realtime=null}if(C.autoRefresh){clearInterval(C.autoRefresh);C.autoRefresh=null}C._stores=C._stores.length?C._stores:await stores();C.loja=PRIVATE_SLUG?(C._stores.find(function(l){return l.slug===PRIVATE_SLUG})||null):(C._stores.find(function(l){return l.id===id})||C._stores[0]||null);C.client=clientFor(C.loja);C.session=null;C.orders=[];C.detalhe=null;C.detalheItens=[];render();if(!C.client){root.innerHTML='<div class="central-shell"><section class="central-card"><h1>Loja não configurada</h1><p>Este link precisa de uma configuração pública do Supabase em <code>config/loja.js</code> e de um slug válido.</p></section></div>';return}var s=await C.client.auth.getSession();C.session=s.data.session||null;if(C.session){if(DEV_MODE){C.orders=[];C.role=null;if(!isDevUser()){C.page='denied-dev';render();return}C.page='dev';render();runStoreDiagnostics();return}await loadRole();if(!C.role||(OWNER_MODE&&C.role!=='owner')){C.orders=[];C.page='denied';render();return}if(OWNER_MODE)C.page='owner';await load();subscribeOrders();C.autoRefresh=setInterval(function(){if(C.session)load(true)},60000)}else loginModal();}
  function authError(e){var m=(e&&e.message||'').toLowerCase();if(m.includes('invalid login credentials'))return 'E-mail ou senha incorretos.';if(m.includes('email not confirmed'))return 'Confirme o e-mail da conta antes de entrar.';if(m.includes('too many requests'))return 'Muitas tentativas. Aguarde alguns minutos.';return e&&e.message||'Não foi possível entrar agora.';}
  async function login(){var email=document.getElementById('central-email').value.trim(),pass=document.getElementById('central-password').value,msg=document.getElementById('central-login-msg'),btn=document.getElementById('central-login-submit');if(!email){msg.textContent='Informe seu e-mail.';return}if(!pass){msg.textContent='Informe sua senha.';return}msg.textContent='Entrando…';btn.disabled=true;var r=await C.client.auth.signInWithPassword({email:email,password:pass});if(r.error){msg.textContent=authError(r.error);btn.disabled=false;return}C.session=r.data.session;document.getElementById('central-login').remove();if(DEV_MODE){C.orders=[];C.role=null;if(!isDevUser()){C.page='denied-dev';render();return}C.page='dev';render();runStoreDiagnostics();return}await loadRole();if(!C.role||(OWNER_MODE&&C.role!=='owner')){C.orders=[];C.page='denied';render();return}if(OWNER_MODE)C.page='owner';await load();subscribeOrders();}
  async function signup(){if(DEV_MODE){toast('Cadastro desativado na Área do Desenvolvedor.');return}var name=(document.getElementById('central-name')||{}).value||'',email=document.getElementById('central-email').value.trim(),pass=document.getElementById('central-password').value,confirm=document.getElementById('central-password-confirm').value,msg=document.getElementById('central-login-msg'),btn=document.getElementById('central-login-submit');if(!name.trim()){msg.textContent='Informe seu nome.';return}if(!email){msg.textContent='Informe seu e-mail.';return}if(pass.length<6){msg.textContent='A senha precisa ter pelo menos 6 caracteres.';return}if(pass!==confirm){msg.textContent='As senhas não conferem.';return}msg.textContent='Criando sua conta…';btn.disabled=true;var r=await C.client.auth.signUp({email:email,password:pass,options:{data:{full_name:name.trim()}}});if(r.error){msg.textContent=authError(r.error);btn.disabled=false;return}if(r.data.session){C.session=r.data.session;document.getElementById('central-login').remove();await loadRole();if(!C.role){C.orders=[];C.page='denied';render();return}await load();subscribeOrders();return}msg.className='central-msg ok';msg.textContent='Cadastro criado. Confirme seu e-mail e aguarde o vínculo à loja.';btn.disabled=false;}
  function showAuthModal(mode){var old=document.getElementById('central-login');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',modalHtml(mode));var f=document.getElementById(mode==='signup'?'central-name':'central-email');if(f)f.focus();}
  async function resetPassword(){var email=document.getElementById('central-email').value.trim(),msg=document.getElementById('central-login-msg');if(!email){msg.textContent='Digite seu e-mail.';return}msg.textContent='Enviando…';var r=await C.client.auth.resetPasswordForEmail(email,{redirectTo:window.location.href.split('#')[0]});if(r.error){msg.textContent=authError(r.error);return}msg.className='central-msg ok';msg.textContent='Se o e-mail existir, você receberá as instruções.';}
  function togglePassword(){var i=document.getElementById('central-password'),b=document.querySelector('[data-central="toggle-password"]');if(!i||!b)return;var show=i.type==='password';i.type=show?'text':'password';b.textContent=show?'Ocultar':'Mostrar';}
  async function load(silent){if(!C.client||!C.session)return;C.loading=!silent;render();var r=await C.client.from('orders').select('*').eq('store_slug',C.loja.slug).order('created_at',{ascending:false}).limit(1000);C.loading=false;if(r.error){C.orders=[];C.loadError=r.error.message;render();showLoginOrError(r.error.message);return}C.orders=r.data||[];C.lastSync=new Date().toISOString();C.loadError=null;render();}
  function subscribeOrders(){if(!C.client||!C.session||!C.loja||!C.client.channel)return;C.realtime=C.client.channel('central-orders-'+C.loja.slug).on('postgres_changes',{event:'*',schema:'public',table:'orders',filter:'store_slug=eq.'+C.loja.slug},function(){load(true)}).subscribe(function(status){if(status==='CHANNEL_ERROR'){C.realtime=null;render();toast('Tempo real indisponível; atualização automática ativa.');}else if(status==='SUBSCRIBED'){render();}});}
  function showLoginOrError(msg){var el=document.createElement('div');el.className='central-modal-fundo';el.innerHTML='<div class="central-modal"><div class="central-modal-icon">⚠</div><h2>Acesso não autorizado</h2><p>A conta precisa estar vinculada a esta loja em <code>public.store_admins</code>.</p><p class="central-tech-error">'+esc(msg)+'</p><div class="acoes"><button class="btn primario" data-central="fechar-erro">Entendi</button></div></div></div>';document.body.appendChild(el);}
  function loginModal(){if(!C.client){toast('Configure o Supabase nesta loja primeiro.');return}showAuthModal('login');}
  async function openDetail(id){var o=C.orders.find(function(x){return x.id===id});if(!o)return;C.detalhe=o;C.detalheItens=[];render();if(!C.client)return;var r=await C.client.from('order_items').select('*').eq('order_id',id).order('created_at',{ascending:true});if(!r.error)C.detalheItens=r.data||[];render();}
  async function saveStatus(){var s=document.getElementById('central-detail-status').value,o=C.detalhe;if(!o||!C.client)return;var r=await C.client.from('orders').update({status:s,updated_at:new Date().toISOString()}).eq('id',o.id).eq('store_slug',C.loja.slug);if(r.error){toast('Não foi possível atualizar: '+r.error.message);return}o.status=s;toast('Status atualizado');render();}
  function csvCell(v){return '"'+String(v==null?'':v).replace(/"/g,'""')+'"';}
  function exportCSV(){var rows=activeOrders(),lines=[['Pedido','Cliente','Telefone','Tipo','Pagamento','Total','Status','Data'].map(csvCell).join(';')];rows.forEach(function(o){lines.push([o.order_number,o.customer_name,o.customer_phone,o.order_type==='delivery'?'Entrega':'Retirada',o.payment_method,o.total,statusLabel(o.status),date(o.created_at)].map(csvCell).join(';'))});var blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pedidos-'+(C.loja&&C.loja.slug||'loja')+'-'+dayKey(new Date())+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},500);toast('CSV exportado');}
  function goPage(p){C.page=p;C.busca='';C.status='all';render();if(C.loja&&!C.client)selectStore(C.loja.id);}
  document.addEventListener('click',function(e){var b=e.target.closest('[data-central]');if(!b)return;var a=b.dataset.central;
    if(a==='copy-private-link'){var link=privateLink();if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(link).then(function(){toast('Link privado copiado')}).catch(function(){var i=document.getElementById('central-private-link');if(i){i.focus();i.select();toast('Selecione e copie o link manualmente')}})}else{var i=document.getElementById('central-private-link');if(i){i.focus();i.select();toast('Selecione e copie o link manualmente')}}return}if(a==='dashboard'||a==='pedidos'||a==='clientes'){goPage(a);return}if(a==='dev'){if(!isDevUser()){toast('Área do Dev disponível somente na rota privada /dev/ para a conta autorizada.');return}goPage(a);return}if(a==='owner'){C.page='owner';render();if(C.role!=='owner')toast('Área exclusiva para a conta com papel owner nesta loja.');return}
    if(a==='dev-refresh'){toast('Testando as configurações das lojas…');runStoreDiagnostics();return}if(a==='dev-owner-link'){var ownerSlug=b.dataset.slug||'',ownerUrl=location.origin+'/dono/?loja='+encodeURIComponent(ownerSlug);if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(ownerUrl).then(function(){toast('Link individual copiado')}).catch(function(){window.prompt('Copie o link individual do proprietário:',ownerUrl)})}else window.prompt('Copie o link individual do proprietário:',ownerUrl);return}if(a==='dev-store-help'){var slug=b.dataset.slug||'',l=(C._stores||[]).find(function(x){return x.slug===slug}),h=(C.storeHealth||{})[slug],issues=h&&h.issues.length?h.issues:storeConfigIssues(l,C._stores);var msg='Diagnóstico da loja: '+(l&&l.nome||slug)+' ('+slug+')\nResultado: '+(h&&h.connection||'Não testado')+'\n\n'+(issues.length?issues.map(function(x,i){return (i+1)+'. '+x}).join('\n'):'Nenhum erro de configuração detectado. Se o login ainda falha, verifique public.store_admins, Auth e RLS no Supabase.');window.alert(msg);return}
    if(a==='dev-copy'){var summary='Sistema V9.2\nLojas cadastradas: '+(C._stores||[]).length+'\nLojas com teste OK: '+Object.keys(C.storeHealth||{}).filter(function(k){return C.storeHealth[k].status==='ok'}).length+'\nLoja: '+(C.loja&&C.loja.nome||'—')+'\nSlug: '+(C.loja&&C.loja.slug||'—')+'\nHost: '+location.host+'\nOnline: '+(navigator.onLine!==false)+'\nSupabase configurado: '+!!C.client+'\nSessão administrativa: '+!!C.session+'\nRealtime: '+!!C.realtime+'\nÚltima sincronização: '+(C.lastSync||'—');if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(summary).then(function(){toast('Resumo copiado')}).catch(function(){toast('Não foi possível copiar automaticamente')});else toast('Seu navegador não permite copiar automaticamente');return}
    if(a==='period'){C.period=b.dataset.period||'all';render();return}
    if(a==='refresh'){load();return}
    if(a==='export-csv'){exportCSV();return}
    if(a==='fechar-login'){var x=document.getElementById('central-login');if(x)x.remove();return}
    if(a==='login'){login();return}if(a==='signup'){signup();return}if(a==='show-signup'){showAuthModal('signup');return}if(a==='show-login'){showAuthModal('login');return}if(a==='toggle-password'){togglePassword();return}if(a==='reset-password'){resetPassword();return}
    if(a==='logout'){if(C.realtime&&C.client){try{C.client.removeChannel(C.realtime)}catch(e){}C.realtime=null}if(C.autoRefresh)clearInterval(C.autoRefresh);if(C.client)C.client.auth.signOut();C.session=null;C.role=null;C.orders=[];C.page='dashboard';if(PRIVATE_SLUG){render();loginModal()}else{render();loginModal()}return}
    if(a==='pedido'){openDetail(b.dataset.id);return}if(a==='fechar-detalhe'){C.detalhe=null;render();return}if(a==='salvar-status'){saveStatus();return}if(a==='fechar-erro'){var m=b.closest('.central-modal-fundo');if(m)m.remove();return}
  });
  document.addEventListener('change',function(e){if(e.target.id==='central-store'){selectStore(e.target.value);return}if(e.target.id==='central-status'){C.status=e.target.value;render();return}if(e.target.id==='central-period'){C.period=e.target.value;render();return}});
  document.addEventListener('input',function(e){if(e.target.id==='central-search'){C.busca=e.target.value;var pos=C.busca.length;render();var x=document.getElementById('central-search');if(x){x.focus();x.setSelectionRange(pos,pos)}}});
  document.addEventListener('keydown',function(e){if(e.key==='Enter'&&document.getElementById('central-login')){e.preventDefault();var b=document.getElementById('central-login-submit');if(b&&b.dataset.central==='signup')signup();else login();}});
  var obs=new MutationObserver(function(){injectNav()});obs.observe(root,{childList:true,subtree:false});window.__centralObserver=obs;
  window.addEventListener('hashchange',function(){if(location.hash==='#pedidos'){goPage('pedidos')}});
  stores().then(function(s){C._stores=s;injectNav();if(DEV_MODE){C.loja=(s.find(function(l){return l.slug===(window.LOJA&&window.LOJA.slug)})||s[0]||window.LOJA||null);if(C.loja&&C.loja.slug&&C.loja.id==null)C.loja.id=C.loja.slug;C.page='dev';selectStore(C.loja&&C.loja.id);return}if(OWNER_MODE&&!PRIVATE_SLUG){root.innerHTML='<div class="central-shell"><section class="central-card"><h1>Link privado incompleto</h1><p>Use o endereço individual enviado pelo administrador, no formato <code>/dono/?loja=SLUG</code>.</p></section></div>';return}if(PRIVATE_SLUG){var target=s.find(function(l){return l.slug===PRIVATE_SLUG});if(target){C.page=OWNER_MODE?'owner':'dashboard';selectStore(target.id)}else{root.innerHTML='<div class="central-shell"><section class="central-card"><h1>Link de loja não configurado</h1><p>O slug <code>'+esc(PRIVATE_SLUG)+'</code> não existe em <code>config/lojas.js</code>. Cadastre a configuração real da loja e publique novamente. Nenhuma outra configuração será reutilizada.</p></section></div>'}return}if(s.length){C.loja=s[0];C.client=clientFor(C.loja);var p=location.hash==='#pedidos'?'pedidos':'dashboard';C.page=p;render();selectStore(C.loja.id);}else injectNav();}).catch(function(){injectNav();});
})();
