(function(){
'use strict';
const cfg=window.SAAS_CONFIG||{},legacy=window.LOJA||{},$=id=>document.getElementById(id);
let db=null,store=null,products=[],cart=new Map();
const slug=new URLSearchParams(location.search).get('slug');
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const numeric=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0};
function msg(t){$('message').textContent=t||''}
function safeImg(url){if(!url)return '';if(/^https:\/\//i.test(url))return url;if(/^(assets|images)\//i.test(url))return new URL('../'+url,location.href).href;return ''}
function settings(){return store?.settings&&typeof store.settings==='object'?store.settings:{}}
function deliveryFee(){return Math.max(0,numeric(settings().delivery_fee??settings().deliveryFee??6.9))}
function minimumOrder(){return Math.max(0,numeric(settings().minimum_order??settings().minimumOrder??0))}
function selectedType(){return $('order-type').value}
function subtotal(){let total=0;cart.forEach(v=>total+=numeric(v.p.price??v.p.preco)*v.qty);return total}
function total(){return subtotal()+(selectedType()==='delivery'?deliveryFee():0)}
function render(){const box=$('products');box.replaceChildren();if(!products.length){const p=document.createElement('p');p.className='muted';p.textContent='Esta loja ainda não publicou produtos.';box.append(p);return}products.forEach(p=>{const card=document.createElement('article');card.className='product';const image=safeImg(p.image_url||p.imagem);if(image){const img=document.createElement('img');img.src=image;img.alt=p.name||p.nome||'Produto';img.loading='lazy';card.append(img)}const body=document.createElement('div');body.className='product-body';const h=document.createElement('h3');h.textContent=p.name||p.nome;const d=document.createElement('p');d.textContent=p.description||p.descricao||p.category||p.categoria||'';const foot=document.createElement('div');foot.className='product-foot';const price=document.createElement('span');price.className='price';price.textContent=money(p.price??p.preco);const btn=document.createElement('button');btn.textContent='Adicionar +';btn.addEventListener('click',()=>{const key=p.id||p.name||p.nome;const item=cart.get(key)||{p,qty:0};item.qty++;cart.set(key,item);renderCart();btn.textContent='Adicionado ✓';setTimeout(()=>btn.textContent='Adicionar +',700)});foot.append(price,btn);body.append(h,d,foot);card.append(body);box.append(card)})}
function renderCart(){let qty=0;cart.forEach(v=>qty+=v.qty);$('cart-count').textContent=qty+' '+(qty===1?'item':'itens');$('cart-total').textContent=money(subtotal());$('checkout').disabled=qty===0;updateCheckout()}
function updateCheckout(){if(!$('subtotal'))return;const delivery=selectedType()==='delivery';$('address-field').classList.toggle('hidden',!delivery);$('change-field').classList.toggle('hidden',$('payment-method').value!=='Dinheiro');$('subtotal').textContent=money(subtotal());$('delivery-fee').textContent=delivery?money(deliveryFee()):'Grátis';$('checkout-total').textContent=money(total());$('send-order').disabled=cart.size===0}
async function init(){if(!slug){$('store-name').textContent='Loja não informada';$('store-description').textContent='Abra o link enviado pelo proprietário.';return}if(!window.supabase||!cfg.url||!cfg.publishableKey){msg('A plataforma ainda não está configurada.');return}db=window.supabase.createClient(cfg.url,cfg.publishableKey);const {data,error}=await db.from('saas_stores').select('id,name,slug,status,whatsapp,address,description,logo_url,settings').eq('slug',slug).eq('status','active').maybeSingle();if(error)throw error;if(!data)throw Error('Não encontramos essa loja ou ela ainda não está publicada.');store=data;$('store-name').textContent=store.name;$('store-description').textContent=store.description||'';$('store-address').textContent=store.address||'';document.title=store.name+' — Cardápio online';if(store.logo_url){const img=document.createElement('img');img.src=safeImg(store.logo_url);img.alt='Logo '+store.name;if(img.src)$('store-logo').replaceChildren(img)}$('store-status').textContent='Loja online';let result=await db.from('saas_products').select('id,name,description,category,price,image_url,available').eq('store_id',store.id).eq('available',true).order('sort_order').order('created_at');if(result.error)throw result.error;products=result.data||[];if(!products.length&&slug==='brasa-burger'&&legacy.slug==='brasa-burger'){products=(legacy.produtos||[]).map(p=>({id:p.id,name:p.nome,description:p.descricao,category:p.categoria,price:p.preco,image_url:p.imagem||p.imagemUrl||'',available:true}));}const methods=Array.isArray(settings().payment_methods)?settings().payment_methods:String(settings().payment_methods||'Pix,Dinheiro,Cartão de crédito,Cartão de débito').split(',').map(s=>s.trim()).filter(Boolean);const select=$('payment-method');select.replaceChildren();(methods.length?methods:['Pix']).forEach(method=>{const opt=document.createElement('option');opt.value=method;opt.textContent=method;select.append(opt)});const deliveryTime=settings().delivery_time||'';if(deliveryTime)$('store-status').textContent='Online · entrega '+deliveryTime;render();renderCart()}
$('checkout').addEventListener('click',()=>{$('checkout-panel').classList.remove('hidden');$('checkout-panel').scrollIntoView({behavior:'smooth',block:'center'});updateCheckout()});
$('order-type').addEventListener('change',updateCheckout);$('payment-method').addEventListener('change',updateCheckout);
$('send-order').addEventListener('click',()=>{const name=$('customer-name').value.trim();if(!name){msg('Informe seu nome para continuar.');$('customer-name').focus();return}if(cart.size===0){msg('Adicione pelo menos um produto.');return}const delivery=selectedType()==='delivery';const sub=subtotal();if(delivery&&minimumOrder()>0&&sub<minimumOrder()){msg('O pedido mínimo para entrega é '+money(minimumOrder())+'.');return}const phone=String(store.whatsapp||'').replace(/\D/g,'');if(phone.length<10||phone.length>15){msg('O WhatsApp comercial desta loja ainda não está configurado corretamente.');return}const address=$('customer-address').value.trim();if(delivery&&!address){msg('Informe o endereço para entrega.');$('customer-address').focus();return}const payment=$('payment-method').value;const customerPhone=$('customer-phone').value.trim();let lines=['Olá! Quero fazer um pedido na '+store.name+'.','', 'DADOS DO CLIENTE','Nome: '+name];if(customerPhone)lines.push('WhatsApp do cliente: '+customerPhone);lines.push('Recebimento: '+(delivery?'Entrega':'Retirada no local'));if(delivery)lines.push('Endereço: '+address);lines.push('','ITENS DO PEDIDO');let sum=0;cart.forEach(v=>{const p=v.p,price=numeric(p.price??p.preco);sum+=price*v.qty;lines.push(v.qty+'x '+(p.name||p.nome)+' — '+money(price*v.qty))});lines.push('','Subtotal: '+money(sum));lines.push('Taxa de entrega: '+(delivery?money(deliveryFee()):money(0)));lines.push('TOTAL: '+money(total()));lines.push('Pagamento: '+payment);if(payment==='Dinheiro'&&$('customer-change').value.trim())lines.push('Troco para: R$ '+$('customer-change').value.trim());const notes=$('customer-notes').value.trim();if(notes)lines.push('Observações: '+notes);lines.push('','Pedido enviado pelo cardápio online Jonash.dev. Aguardo a confirmação.');const url='https://wa.me/'+phone+'?text='+encodeURIComponent(lines.join('\n'));const opened=window.open(url,'_blank','noopener,noreferrer');if(!opened){msg('O navegador bloqueou a nova aba. Use este link para continuar: '+url);return}msg('Seu pedido foi preparado no WhatsApp. Confira os itens e toque em Enviar para concluir.')});
init().catch(e=>{console.error(e);$('store-name').textContent='Não foi possível abrir a loja';msg(e.message||'Verifique a conexão e tente novamente.')});
})();
