(function(){'use strict';
var cfg=window.LOJA&&window.LOJA.supabase||{}, api=window.supabase, client=null;
if(api&&cfg.enabled&&cfg.url&&cfg.publishableKey) client=api.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
var app=document.getElementById('app'), bars=document.querySelectorAll('.progress i'), state={step:1,user:null,company:{}};
function esc(v){return String(v||'').replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]})}
function msg(t){return '<div class="error">'+esc(t)+'</div>'}
function progress(){bars.forEach(function(b,i){b.classList.toggle('on',i<state.step)})}
async function getSession(){if(!client)return null;var r=await client.auth.getSession();return r.data&&r.data.session}
function render(){progress();if(state.step===1){app.innerHTML='<h1>Crie sua conta</h1><p>Você será o dono da sua empresa e terá acesso ao painel administrativo.</p><div id="err"></div><form id="f1"><div class="grid"><div class="field full"><label>Seu nome</label><input name="name" autocomplete="name" required placeholder="Ex.: João da Silva"></div><div class="field"><label>WhatsApp</label><input name="phone" autocomplete="tel" placeholder="(00) 00000-0000"></div><div class="field"><label>E-mail</label><input name="email" type="email" autocomplete="email" required placeholder="voce@empresa.com"></div><div class="field"><label>Senha</label><input name="password" type="password" minlength="8" autocomplete="new-password" required placeholder="Mínimo de 8 caracteres"></div></div><button>Criar conta e continuar</button></form><a class="link" href="../entrar/">Já tenho uma conta</a>';
document.getElementById('f1').onsubmit=async function(e){e.preventDefault();if(!client){document.getElementById('err').innerHTML=msg('Configure o Supabase em config/loja.js antes de usar o cadastro.');return}var f=new FormData(e.target);var b=e.target.querySelector('button');b.disabled=true;document.getElementById('err').innerHTML='';try{var r=await client.auth.signUp({email:String(f.get('email')).trim().toLowerCase(),password:String(f.get('password')),options:{data:{full_name:String(f.get('name')).trim(),phone:String(f.get('phone')||'').trim()},emailRedirectTo:location.origin+location.pathname}});if(r.error)throw r.error;state.user=r.user;if(!r.session){app.innerHTML='<div class="success"><div class="check">✉️</div><h1>Confirme seu e-mail</h1><p>Enviamos um link de confirmação. Depois de confirmar, volte para esta página para continuar criando sua hamburgueria.</p><a class="link" href="../entrar/">Ir para entrar</a></div>';return}state.step=2;render()}catch(err){document.getElementById('err').innerHTML=msg(err.message||'Não foi possível criar a conta.')}finally{b.disabled=false}}}else if(state.step===2){app.innerHTML='<h1>Crie sua hamburgueria</h1><p>Essa empresa será vinculada à sua conta como <b>OWNER</b>. Você poderá administrar produtos, pedidos e equipe.</p><div id="err"></div><form id="f2"><div class="grid"><div class="field full"><label>Nome da empresa</label><input name="company" required placeholder="Ex.: Brasa Burger"></div><div class="field"><label>Nome da loja</label><input name="store" placeholder="Ex.: Brasa Burger Centro"></div><div class="field"><label>WhatsApp da loja</label><input name="whatsapp" placeholder="(00) 00000-0000"></div><div class="field"><label>Telefone</label><input name="phone" placeholder="(00) 0000-0000"></div><div class="field"><label>Plano inicial</label><select name="plan"><option value="PRO">PRO — R$ 97/mês</option><option value="STARTER">STARTER — R$ 49/mês</option><option value="PREMIUM">PREMIUM — R$ 197/mês</option></select></div><div class="field full"><label>Endereço</label><input name="address" placeholder="Rua, número, bairro, cidade - UF"></div></div><button>Criar minha empresa</button></form>';
document.getElementById('f2').onsubmit=async function(e){e.preventDefault();var f=new FormData(e.target),b=e.target.querySelector('button');b.disabled=true;document.getElementById('err').innerHTML='';try{var s=await getSession();if(!s)throw new Error('Sua sessão expirou. Entre novamente para continuar.');var address={text:String(f.get('address')||'').trim()};var r=await client.rpc('create_owner_company',{p_company_name:String(f.get('company')).trim(),p_store_name:String(f.get('store')||'').trim()||null,p_phone:String(f.get('phone')||'').trim()||null,p_whatsapp:String(f.get('whatsapp')||'').trim()||null,p_email:s.user.email,p_plan_code:String(f.get('plan')),p_address:address,p_hours:[]});if(r.error)throw r.error;state.company=r.data;state.step=3;render()}catch(err){var text=err.message||'';if(text.includes('OWNER_ALREADY_HAS_COMPANY'))text='Esta conta já possui uma empresa. Entre no painel para administrá-la.';if(text.includes('function')&&text.includes('does not exist'))text='A migration de onboarding ainda não foi executada no Supabase.';document.getElementById('err').innerHTML=msg(text)}finally{b.disabled=false}}}else{var c=state.company||{};app.innerHTML='<div class="success"><div class="check">✅</div><h1>Empresa criada com sucesso!</h1><p>Sua hamburgueria já está vinculada à sua conta. Agora você pode configurar o cardápio e começar a receber pedidos.</p><div class="summary"><b>'+esc(c.store_name||c.organization_name)+'</b><span>Link interno: /'+esc(c.store_slug||c.organization_slug)+'</span><span>Plano: '+esc(c.plan_code||'PRO')+' • teste inicial</span></div><button id="go">Abrir meu painel</button><a class="link" href="../">Voltar ao cardápio</a></div>';document.getElementById('go').onclick=function(){location.href='../painel/'}}}
render();
})();
